### ISSUE TITLE
Unable to render images with sixel protocol & ratatui-image

### ISSUE THREAD

**Issue by orhun** [raphamorim/rio#639] opened 2024-09-03 07:25 UTC
I tried the image rendering out from the `main` branch using [`ratatui-image`](https://github.com/benjajaja/ratatui-image)'s demo (`cargo run --example demo --features crossterm`):

![image](https://github.com/user-attachments/assets/22c2a466-5d7c-46eb-8ec0-af11aa6543df)

Meanwhile in wezterm:

![image](https://github.com/user-attachments/assets/cf1c09a9-8cd2-46f4-96d0-097c6fb6768f)

How can I debug this? 🤔

_Originally posted by @orhun in https://github.com/raphamorim/rio/issues/38#issuecomment-2325722137_

**Comment by raphamorim** [comment] 2024-09-03 14:17
well at least now is better...

<img width="912" alt="Screenshot 2024-09-03 at 16 17 16" src="https://github.com/user-attachments/assets/bdd951e6-73b3-41dd-8a8d-7be850cfe452">

will keep debuging

**Comment by raphamorim** [comment] 2024-09-03 14:19
actually i get same result with wezterm 

<img width="1004" alt="Screenshot 2024-09-03 at 16 19 10" src="https://github.com/user-attachments/assets/46e4e073-69f2-432d-8f23-8a67b1323934">

**Comment by raphamorim** [comment] 2024-09-03 14:19
can you try again @orhun ?

**Comment by orhun** [comment] 2024-09-03 17:58
Pulled from latest `main` and unfortunately it's still the same for me.

![image](https://github.com/user-attachments/assets/96a5f5d1-aea2-4787-8dde-0fbac08e6ea2)

**Comment by raphamorim** [comment] 2024-09-03 18:00
Will try to reproduce on my arch

**Comment by orhun** [comment] 2024-09-03 18:02
Cool, let me know if you need any additional info

**Comment by raphamorim** [comment] 2024-09-08 20:09
Ok figured out through this discussion, https://discourse.iced.rs/t/images-arent-properly-loading/84/10 and this PR https://github.com/iced-rs/iced/pull/2259

"So, it turns out that wgpu [has to use heuristics](https://github.com/gfx-rs/wgpu/blob/004e3efe84a320d9331371ed31fa50baa2414911/wgpu-hal/src/gles/mod.rs#L371) to guess that the texture we are creating will be used as TEXTURE_2D_ARRAY rather than TEXTURE_2D, and OpenGL needs to know that ahead of time, otherwise it will refuse to bind it because of type mismatch.

The real fix should be on wgpu side, but that seems to be known and not obvious problem.
So in the meantime, I just increased default layers allocation in the atlas to 2. That way wgpu will see layer depth 2 and correctly assume that we want to use this texture as TEXTURE_2D_ARRAY"

(basically worked for me because i am using vulkan)

pushed a commit to fix it based on iced PR. closing this issue for now lemme know anything

**Closed by raphamorim** 2024-09-08 20:09 UTC
Labels: Sixel, Image-protocols

**Comment by orhun** [comment] 2024-09-08 20:29
Thanks for your work on this!
