### ISSUE TITLE
Layout support

### ISSUE THREAD

**Issue by bonfiresh** [raphamorim/rio#477] opened 2024-03-23 00:22 UTC
It's really useful to consider supporting layouts like Kitty does

```conf
enabled_layouts vertical,horizontal,grid,fat,tall,stack
map alt+shift+v goto_layout vertical
map alt+shift+h goto_layout horizontal
map alt+shift+g goto_layout grid
map alt+shift+f goto_layout fat
map alt+shift+t goto_layout tall
map alt+shift+s goto_layout stack
```

![g(1)](https://github.com/raphamorim/rio/assets/57741172/e5ad2fa0-718d-4f70-bff4-7b80551d07c1)
![v(1)](https://github.com/raphamorim/rio/assets/57741172/78e9975e-9801-44db-a9a1-c4d06241d8ce)
![h(1)](https://github.com/raphamorim/rio/assets/57741172/53622cdf-1310-4a1b-b1bb-f2432957e7ca)

**Comment by raphamorim** [comment] 2024-04-25 11:50
Hey @bonfiresh thanks for the issue,

I am working on that for 0.1.x versions but I will close this issue since is a duplicate of #184 .

**Closed as completed by raphamorim** 2024-04-25 11:50 UTC
