### ISSUE TITLE
error after install

### ISSUE THREAD

**Issue by tunmie** [raphamorim/rio#300] opened 2023-10-23 01:44 UTC
---------------------------
Rio: Runtime Error
---------------------------
panicked at 'Error in Surface::configure: Validation Error

Caused by:
    Invalid surface
', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.16.3\src\backend\direct.rs:734:18

Press Ctrl-C to Copy
---------------------------
OK   
---------------------------

**Comment by raphamorim** [comment] 2023-10-23 06:34
Hey @tunmie thanks for the issue

Which Rio version is that?

**Comment by tunmie** [comment] 2023-10-29 15:26
the latest release version on windows

**Comment by raphamorim** [comment] 2023-11-07 08:26
hey @tunmie could you try with this version https://github.com/raphamorim/rio/releases/tag/v0.0.27

**Comment by raphamorim** [comment] 2023-11-09 13:52
I am closing this issue for now because `C:\Users\runneradmin.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.16.3\src\backend\direct.rs:734:18`

Could reproduce with old rio version and now and looks is gone, also noticed the version you are using the old version that targets wgpu-0.16.3 but new rio is using wgpu-0.18.

**Closed by raphamorim** 2023-11-09 13:52 UTC
