### ISSUE TITLE
Can't use bbedit command within rio to open a file in bbedit

### ISSUE THREAD

**Issue by ehjmx** [raphamorim/rio#99] opened 2023-06-18 09:19 UTC
Using 
`bbedit .config/rio/config.toml`

I get the following error message:
You must allow the application which is running `bbedit` to send events to the BBEdit application.
Please make appropriate changes in your Security & Privacy system preferences,
or contact your terminal/IDE application's developer for assistance.
bbedit: error: -1743

rio canary-2316d6de8782f6eaa94121c508c7798b303ca415 macOS 13.4 on a M2 MBP 2022.

Using the old config file format and release 0.0.61 I get the same error message.

**Comment by raphamorim** [comment] 2023-06-18 09:22
It worked for me in lastest main but I had to give macos permissions to beedit ("macos this app cannot be installed because its integrity could not be verified", the clicked open)

<img width="961" alt="Screenshot 2023-06-18 at 11 21 02" src="https://github.com/raphamorim/rio/assets/3630346/2143af4d-974f-45ce-8550-83535901cc03">
<img width="1197" alt="Screenshot 2023-06-18 at 11 21 18" src="https://github.com/raphamorim/rio/assets/3630346/1882c984-6ae5-4cfc-bab3-c195602cb33c">

**Comment by ehjmx** [comment] 2023-06-18 16:33
@raphamorim Indeed for a second I thought that I saw the pop up aksing me to allow Rio to send events to BBEdit but even after closing all Windows or putting them in the dock I couldn't see/find it. 

In System Preferences Security & Privacy the screenshot shows that BBEdit is allowed to control Terminal and Finder, while Terminal is allowed to send System Events and control BBEdit and wezterm is allowed to control BBEdit. 

<img width="928" alt="Bildschirmfoto 2023-06-18 um 18 20 01" src="https://github.com/raphamorim/rio/assets/75489369/56bf9123-4b01-4840-a891-22c39fb4bdfd">

After deleting Rio and reinstalling it BBEdit launches and even loads the file but if I try to open a second file using the same command but a different file e.g.
`bbedit weekly_get_latest.sh`

I get the above error message. 

Parts of the issue are solved and it was a matter of reinstalling Rio but it would really be nice if it works more than once.

**Comment by raphamorim** [comment] 2023-06-18 18:32
Hmm, I agree is odd. I couldn't reproduce but found this issue https://github.com/warpdotdev/Warp/issues/1127 that looks pretty much as your case. Added the suggested fix for the latest Rio build please confirm if it had fixed.

**Comment by ehjmx** [comment] 2023-06-20 07:30
The canary-94fb71f8469818253106573b2ca737c2015e3951 behaved as expected. I was asked to allow Rio to control BBEdit etc. 

I can now open a file more than once via bbedit from the cmd. Thanks for the quick fix.

**Comment by raphamorim** [comment] 2023-06-20 07:33
That's great, about the DPI/Factor rendering issues in Rio, should be fixed in the next version. Have a major refactor/fixes on the renderer: https://twitter.com/raphamorims/status/1671052328827338754

**Closed by raphamorim** 2023-06-20 07:33 UTC
Labels: bug
