### ISSUE TITLE
[Feature Request]: Optimize memory consumption

### ISSUE THREAD

**Issue by SteveLauC** [raphamorim/rio#665] opened 2024-09-13 08:04 UTC
Hi, thanks for the project, I am now using Rio as my daily driver terminal! I love the neat tab!

Though I found that the memory consumption of Rio is relatively high compared to other terminal apps, here is a table that shows the comparison, note that they are all newly-spawned processes, memory usage will increase when you use them for a longer time:

| Rio | Alacritty | Terminal.app | Iterm2 |   
|----|----------|--------------|-------|
| 190MB| 77MB|42MB              | 39MB|

## My Env

```sh
$ rio --version
rioterm 0.1.13

$ uname -a
Darwin Steves-MacBook-Air.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:52 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8103 arm64
```

**Comment by raphamorim** [comment] 2024-09-13 08:06
Thank you for the issue! I am fixing this for the next version, if you would like you can start using/testing main branch (nightly release), should reduce a very good amount of memory consumption.

**Comment by SteveLauC** [comment] 2024-09-13 08:36
> if you would like you can start using/testing main branch (nightly release), should reduce a very good amount of memory consumption.

Yeah, definitely, I will try to build it from src and give it a test when I have time:)

**Comment by raphamorim** [comment] 2024-09-13 08:50
However still not gonna be the best (nightly right now) but I plan to address it on this version, basically big part of the issue is that Rio doesn't drop the memory related to font data. I am working on it for new version 🙏

**Comment by SteveLauC** [comment] 2024-09-13 09:02
Thanks for working on the issue, generally no worries, 200MB won't stop me using it at all😆

**Comment by raphamorim** [comment] 2024-09-17 07:42
@SteveLauC next version should drop memory usage by around 75%, of course that more you use the terminal more memory will drain because need to keep the string bytes stored for historic but 200mb for newly-spawned processes can't be acceptable 👌 😆 
￼
<img width="771" alt="PNG image" src="https://github.com/user-attachments/assets/94cf767a-d201-4d4a-84cb-2c674db328a8">

**Comment by raphamorim** [comment] 2024-09-17 07:42
Closing this issue for now but any other thing please let me know 🙏

**Closed by raphamorim** 2024-09-17 07:42 UTC

**Comment by SteveLauC** [comment] 2024-09-17 07:46
Looks forward to the next release!
