### ISSUE TITLE
There is an issue while rendering unicode character, please implement fallback font

### ISSUE THREAD

**Issue by hucancode** [raphamorim/rio#266] opened 2023-10-02 02:30 UTC
I'm currently using "FiraCode Nerd Font" as my main font. It doesn't support japanese characters but in my system there are some that does.
Now when I try to type in japanese, characters aren't recognized, like this
![image](https://github.com/raphamorim/rio/assets/15852849/6751914c-7f67-439d-9389-3e5d39211527)
Input: bello, こんにちは、源氏です
Not sure if this is windows only or it is universal. Please implement fallback font for unicode people.

OS: Windows 10, WSL2
Rio version: 0.0.19

**Comment by lost22git** [comment] 2023-10-02 07:32
+1

![Screenshot 2023-10-02 153119](https://github.com/raphamorim/rio/assets/65008815/a2f4efa2-4463-4898-afb5-233e5fff3ab1)

**Comment by raphamorim** [comment] 2023-10-02 07:35
Agree, it is something on my todo list. It also connects with #191 (unicode normalization), would the possibility of adding fallback fonts would help?

```toml
[fonts]
extra = ["font1", "font2"]
```

This API isn't the best and might gonna be removed at some moment but if it helps would add it for now.

**Comment by raphamorim** [comment] 2023-10-02 07:46
Btw cannot reproduce with MacOS but might be coming from the extra fonts sugarloaf loads for macos <img width="477" alt="Screenshot 2023-10-02 at 09 46 05" src="https://github.com/raphamorim/rio/assets/3630346/117732fb-6e9a-4680-8a01-ca5fd445d5dc">

**Comment by raphamorim** [comment] 2023-10-02 08:42
Ok, fixed for Microsoft windows in the main

before

<img width="297" alt="Screenshot 2023-10-02 at 10 25 04" src="https://github.com/raphamorim/rio/assets/3630346/964abf99-5154-49b9-9d56-3f4a1bdc8480">

after

![Screenshot 2023-10-02 at 10 42 06](https://github.com/raphamorim/rio/assets/3630346/9cdec3ab-0082-4d42-b524-974cfe6b9887)

let me know anything else, closing this issue.

**Closed by raphamorim** 2023-10-02 08:42 UTC
