### ISSUE TITLE
Incorrect cursor position when using multi-byte characters

### ISSUE THREAD

**Issue by fsouza** [raphamorim/rio#127] opened 2023-07-08 19:30 UTC
Thanks for working on Rio! :) I gave it a shot today, and noticed that the cursor position is incorrect when using multi-byte characters. For example, I have my $PROMPT (aka PS1) set to `％ ` (`％`, not `%`), and that gets Rio confused:

https://github.com/raphamorim/rio/assets/108725/0e580d7c-8765-4aea-aa3a-e29714bc0fd8

As you can see in the recording, changing the PROMPT to not use multi-byte characters fixes the issue.

**Comment by raphamorim** [comment] 2023-07-08 21:00
Thank you @fsouza for the detailed report, hmm that's weird. my PROMPT is `%F{blue}%2~%f ${vcs_info_msg_0_} ~` and it does work correctly for me:

Rio/Alacritty/Terminal.app

![Screenshot 2023-07-08 at 23 00 11](https://github.com/raphamorim/rio/assets/3630346/e74d9348-fae8-4741-a78f-950db3bfac94)
![Screenshot 2023-07-08 at 23 00 23](https://github.com/raphamorim/rio/assets/3630346/2e0cb5c6-828f-41f2-b581-afbcfb9ba2f2)
<img width="582" alt="Screenshot 2023-07-08 at 23 00 45" src="https://github.com/raphamorim/rio/assets/3630346/164db41c-a316-41b6-8528-998df1a3af97">

**Comment by raphamorim** [comment] 2023-07-09 07:40
hmm, actually nevermind could reproduce and figured out the reason. Marking as bug and putting the fix to next release.

**Comment by raphamorim** [comment] 2023-07-12 10:36
Hey @fsouza, could you try with latest main?

![Screenshot 2023-07-12 at 12 32 19](https://github.com/raphamorim/rio/assets/3630346/da345089-3d4c-4d05-8b0f-d0665f1e1347)
![Screenshot 2023-07-12 at 12 32 30](https://github.com/raphamorim/rio/assets/3630346/cd9a06ec-3a4f-4afd-b591-296603df3a4d)
![Screenshot 2023-07-12 at 12 32 46](https://github.com/raphamorim/rio/assets/3630346/3d08b350-e1b2-4ebb-9338-872c4abca1f2)

**Comment by fsouza** [comment] 2023-07-12 12:03
It works, thank you very much! 🎉

**Comment by raphamorim** [comment] 2023-07-12 12:04
Noice! Thank you for checking it @fsouza

**Closed by raphamorim** 2023-07-12 12:04 UTC
Labels: bug
