### ISSUE TITLE
Issue rendering ➜ & ✔ glyphs

### ISSUE THREAD

**Issue by icaromh** [raphamorim/rio#160] opened 2023-07-26 12:48 UTC
Hey 👋🏻 

First of all, fantastic project.

I've been using [ohmyz.sh](https://ohmyz.sh/) with [robbyrussell](https://github.com/ohmyzsh/ohmyzsh/wiki/Themes#robbyrussell) theme + Dracula colors.
And I faced some issues rendering the characters `➜` and `✔`, they appear cropped. I've tried to change the terminal font sizing, without success. 

For reference, below is a screenshot comparing `iterm` vs `rio`:
<img width="612" alt="image" src="https://github.com/raphamorim/rio/assets/3057676/d46cba52-ba8a-4cf6-baad-dc3998dd1962">

Not sure, but it can be related to #135?

____

System:

- Rio 0.0.14 (20230528.115631) installed via brew
- robbyrussell
- oh-my-zsh
- macos (MacOS 13.4.1)
- Monaco font

**Comment by ralgozino** [comment] 2023-07-26 17:07
Yes, I can confirm is the same thing

**Comment by raphamorim** [comment] 2023-07-26 23:41
Fixed at main

![Screenshot 2023-07-27 at 01 39 10](https://github.com/raphamorim/rio/assets/3630346/2bc22832-dba6-4d7c-ba27-cae3a566ca9c)

<img width="747" alt="Screenshot 2023-07-27 at 01 41 00" src="https://github.com/raphamorim/rio/assets/3630346/36ce4438-bbde-4e9d-ae93-3413732da46c">

**Comment by ralgozino** [comment] 2023-07-27 08:21
Now I'm not sure it was the same issue... 😆 

This is my shell running `main`:
<img width="1055" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/be4a1d6f-c999-4a59-acb4-75c57905b82e">

iTerm2 for reference:
<img width="1127" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/e8310aba-8bc5-4f9a-9c12-74a45746b3f6">


I think the difference is that these are 2-width glyphs though (and they come from [nerd fonts)](https://github.com/ryanoasis/nerd-fonts), should I open another issue?

**Comment by raphamorim** [comment] 2023-07-27 08:34
Weird though that even your checkmark wasn't affect by the change.

I don't believe the icons should 2 char width, I know Iterm2 (I think terminal.app too) does that way but I feel is more for the "style" than follow ANSI rules. For example Alacritty and Kitty:

<img width="471" alt="Screenshot 2023-07-27 at 10 30 45" src="https://github.com/raphamorim/rio/assets/3630346/18f8f3cb-37ea-40ea-904d-194a6561a1a1">
<img width="311" alt="Screenshot 2023-07-27 at 10 33 52" src="https://github.com/raphamorim/rio/assets/3630346/7d0921fc-bf64-4500-b41b-fd52651c9073">

Although I plan to allow the user define if want a multi width for a specific font in the next version.

**Comment by raphamorim** [comment] 2023-07-27 08:35
> This is my shell running main:

Was it cropping before as well right?

**Comment by ralgozino** [comment] 2023-07-27 08:49
> > This is my shell running main:
> 
> Was it cropping before as well right?

It started cropping with the fix to #148 

There's some improvement on `main` though (top window is Rio 0.0.14, bottom `main`):
<img width="1256" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/74025a21-ad53-4f0e-9968-9e96495050a4">

**Comment by raphamorim** [comment] 2023-07-27 08:53
Very interesting because I am not able to reproduce it, before at least for me the icons always have been rendered with 2x less width/height to fix 1 char width. Like the image below

<img width="429" alt="Screenshot 2023-07-27 at 10 51 20" src="https://github.com/raphamorim/rio/assets/3630346/e844422d-ae98-45ce-b02f-9bd2ebe05d7f">

So my assumption was ➜ & ✔ glyphs were coming from unicode fonts instead of icons which was the case (at least for me)

Which font/font-size are you using @ralgozino ?

**Comment by raphamorim** [comment] 2023-07-27 08:53
Would you mind share the configuration file?

**Comment by ralgozino** [comment] 2023-07-27 08:57
16, but I tested with 14 and 18 and got the same result

```shell
❯ cat ~/.config/rio/config.toml
```

```toml
font = "VictorMono Nerd Font"
font-size = 16
window-width=1200
window-height=900
```

I don't know if it's related, but the `❯` glyph is smaller than it should be:
<img width="1221" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/ea4e0908-1c88-453b-9a77-e47cd643938a">

**Comment by raphamorim** [comment] 2023-07-27 08:59
Because Rio is bundling the Nerd Font so you wouldn't need to have a font with nerd fonts patched, but it has been considering the icons aren't coming from a text font.

**Comment by raphamorim** [comment] 2023-07-27 09:00
Can you just check if you get same results using a system font? (just for a sanity check)

**Comment by ralgozino** [comment] 2023-07-27 09:22
> ah I got it, `VictorMono Nerd Font` has the icons inside of the font right?

correct

> Can you just check if you get same results using a system font (menlo, consolas for example)? (just for a sanity check)

commenting out the config for the font and font-size, so using the default font (I believe it uses an integrated font, right?) it renders better but the glyphs are still a little small:

<img width="1248" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/fa33448a-317b-4190-8e89-5e4d2d5b819e">

**Comment by raphamorim** [comment] 2023-07-27 09:38
Gotcha, ok so logically make sense: sugarloaf is considering text font as text but it can happen to have icons that aren’t monospaced. This is something that needs a fix.

regarding the small icons is a very tricky issue because iterm2 and terminal.app doesn’t follow strictly the ANSI rules regarding cells. Icons aren’t characters with width bigger than 1.

kitty has same issue https://github.com/kovidgoyal/kitty/issues/1463

> Nerd fonts use private use unicode characters. These are all single cell characters. If you want them rendered in more than a single cell, you have to follow them with one or more spaces, then kitty will use the space cells to render the character as needed.

It’s one valid approach.

I think for now fix the renderer to understand glyph width and reposition to 1 cell.

Then allow people to configure width of specific characters or fonts. So could say “I want all the icons as char-width 2”.

But support icons as 2 cells for special unicode can’t be the default behaviour (only by configuration)

**Comment by ralgozino** [comment] 2023-07-27 10:55
> But support icons as 2 cells for special unicode can’t be the default behaviour (only by configuration)

as a user, I find this is acceptable. I understand that no everybody uses this glyphs or complex prompts :-)

FYI: I tried using `Victor Mono` as font instead of the patched version `VictorMono Nerd Font` as suggested in the linked issue, and the result is similar to using the default font, i.e. glyphs are rendered better but still small:

<img width="1226" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/806c0020-998e-4e5e-89fd-a2a7fc9a46e3">

**Comment by raphamorim** [comment] 2023-07-27 16:04
@ralgozino can you test later using the branch dynamic-font-calculator? https://github.com/raphamorim/rio/tree/dynamic-font-calculator

**Comment by ralgozino** [comment] 2023-07-27 16:26
I don't notice any difference... what should I be looking at?
<img width="1242" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/473fd2e5-1a8e-47b5-b8f6-d00e5daca4b4">

**Comment by raphamorim** [comment] 2023-07-27 16:43
Now your icons aren't cropped at least 🙏 

![image](https://github.com/raphamorim/rio/assets/3630346/bfe10096-e1d8-44fa-a656-c879024bea9c)

**Comment by raphamorim** [comment] 2023-07-27 16:44
is ➜ & ✔ glyphs ok?

The problem is just the underline right?

**Comment by ralgozino** [comment] 2023-07-28 13:45
Hi @raphamorim 

here are some tests:

default config:
<img width="1312" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/24455a1e-f76b-4fa1-855d-2e6971ac6841">

using `Victor Mono` (without the Nerd font glyphs):
<img width="1312" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/1a3824ec-fee1-4b47-8590-95d1240557c3">

using `VictorMono Nerd Font` (Victor Mono patched with the Nerd font glyphs):
<img width="1312" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/d62a7e50-34d5-4e16-b243-525f9b72ed1d">

so, I'd say that the smaller glyphs problem is common to all the cases, but using `Victor Mono` also doesn't draw the underline.

I noticed that using `Victor Mono` the italics also don't get rendered correctly:
<img width="1312" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/3233a09d-2dc2-46dc-9065-9f500a0bb10e">
<img width="1312" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/d8a47bc5-dbff-422b-997b-fe45481b2fcc">
(see the difference in the comments)

**Comment by raphamorim** [comment] 2023-07-28 14:12
> so, I'd say that the smaller glyphs problem is common to all the cases, but using Victor Mono also doesn't draw the underline.

That's expected correctly, the smaller icons should be default behaviour until Rio has the configuration to allow it with char width 2.

Regarding Victor Mono yes, I download yesterday and honestly everything looks weird. i will need to investigate that one tbh.

**Comment by ralgozino** [comment] 2023-07-28 14:33
the good thing is that glyphs are not being cut anymore 😄  🎉

**Comment by raphamorim** [comment] 2023-07-28 16:54
Ok, I will close this one and open an issue regarding Victor Mono. Thanks @icaromh @ralgozino for reporting and testing.

**Closed by raphamorim** 2023-07-28 16:54 UTC
Labels: bug
