### ISSUE TITLE
cant load in osx

### ISSUE THREAD

**Issue by mastercyb** [raphamorim/rio#84] opened 2023-06-06 00:02 UTC
<img width="658" alt="Screen Shot 2023-06-06 at 00 02 21" src="https://github.com/raphamorim/rio/assets/410789/5c012d5d-204a-42ed-94d0-6ec3f0b028f1">

**Comment by raphamorim** [comment] 2023-06-06 06:45
Hey there @mastercyb,

Thanks for the issue report, what's your macos version?

**Comment by ioloie** [comment] 2023-06-07 10:36
I'm seeing this issue with  MacOs Monterey 12.6.5 (intel)

**Comment by OlshaMB** [comment] 2023-06-07 11:36
I had the same issue, I just compiled the new version from source and also in the current stage it's better to compile it from source

**Comment by raphamorim** [comment] 2023-06-08 11:36
@ioloie @mastercyb other question: what's the default shell (e.g: fish, zsh, bash)?

**Comment by ioloie** [comment] 2023-06-08 12:43
Zsh

**Comment by OlshaMB** [comment] 2023-06-09 18:53
I had the same problem and i use fish. So i build it from scratch and it worked

**Comment by ioloie** [comment] 2023-06-20 08:54
I've just updated to MacOS Ventura (13.4) and the latest master works now so it looks like an OS specific issue

**Comment by raphamorim** [comment] 2023-06-20 09:46
Thanks for updating the issue @ioloie 

Yea, I saw it happening in older macs before (Big Sur) but didn't know it wasn't working in Ventura.

The root cause of the issue if because Rio does a fork (instead of spawn) of the process and it doesn't work in old MacOS.

For now I will close this issue, but believe will be good to add an information that Rio consider Ventura as minimal requirement of OS version.

<img width="656" alt="Screenshot 2023-06-20 at 11 00 49" src="https://github.com/raphamorim/rio/assets/3630346/19923cf1-1e09-4753-bc0d-bb6e9658bbb1">

**Closed by raphamorim** 2023-06-20 09:46 UTC
Labels: bug
