### ISSUE TITLE
"Regression" in italics handling on v0.0.19

### ISSUE THREAD

**Issue by ralgozino** [raphamorim/rio#234] opened 2023-09-19 12:07 UTC
On v0.0.18 I get proper italics for example for comments in VIM instead of just the font hinted (with `Victor Mono`).

Here's a screenshot with v0.0.18 on the left and v0.0.19 on the right, notice the difference in the comments' font rendering:
<img width="1792" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/7b53e0e4-72db-426f-9c39-bcfa506624ba">

I'd prefer the behaviour that was on 0.0.18.

Here's my config in case is just a configuration issue:

```toml
blinking-cursor = true

[window]
width = 1200
height = 900

[fonts]
family = "Victor Mono"

[fonts.regular]
family = "Victor Mono"
style = "regular"
weight = 400

[fonts.bold]
family = "Victor Mono"
style = "bold"
weight = 800

[fonts.italic]
family = "Victor Mono"
style = "italic"
weight = 400

[fonts.bold-italic]
family = "Victor Mono"
style = "bold italic"
weight = 800

[navigation]
mode = "NativeTab"

[developer]
log-level = "INFO"
```

**Comment by raphamorim** [comment] 2023-09-23 21:36
@ralgozino can you try again with the logs? (I've added an error log to whenever the font is not found in the main)

**Comment by raphamorim** [comment] 2023-09-23 21:38
Ah actually I misunderstood the issue, the font is found but is rendering differently right?

**Comment by raphamorim** [comment] 2023-09-23 21:43
For me is working as before 🤔 

<img width="482" alt="Screenshot 2023-09-23 at 23 43 20" src="https://github.com/raphamorim/rio/assets/3630346/d174b2ac-58aa-45a9-9dba-2b0edee132d5">

**Comment by raphamorim** [comment] 2023-09-23 21:44
My config <img width="370" alt="Screenshot 2023-09-23 at 23 44 27" src="https://github.com/raphamorim/rio/assets/3630346/3cb2c43a-c57e-484e-8a4d-f9fcfce32817">

**Comment by ralgozino** [comment] 2023-10-03 15:57
Hi @raphamorim 

Sorry for the delayed answer, I've just tested with 0.0.22, rio uses the `oblique` style instead of `italics` in my case:
<img width="1792" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/b40480d4-fddb-4e70-bfcf-8aa5bcb03e2a">

Notice that also `underline` is not working anymore.

Doing some tests, I found that if I delete the oblique `otf` font file from my system, then rio finds the italic and uses it.

**Comment by raphamorim** [comment] 2023-10-03 16:20
Thank you @ralgozino ,

VictorMono has been on top 3 "weird" behaviour with rio, underline with fira code:

<img width="613" alt="Screenshot 2023-10-03 at 18 17 14" src="https://github.com/raphamorim/rio/assets/3630346/34e047bf-d7a6-4777-a655-e9df52a07e22">

I am rewriting sugarloaf to stretch/reposition glyphs should fix VictorMono underline and other fonts that have bigger/smaller stroke of underline.

Will be closing this issue, but will be keeping an eye on it. I can't reproduce tbh, I have oblique and italic of victor mono and it always match up with italic.

**Closed by raphamorim** 2023-10-03 16:20 UTC
Labels: bug
