### ISSUE TITLE
can't figure out how to bind arrow keys properly

### ISSUE THREAD

**Issue by fdncred** [raphamorim/rio#222] opened 2023-09-14 12:01 UTC
I go back and forth between WezTerm and Rio, trying to switch to Rio. The latest thing that is preventing this switch is that I'm trying to use the [yazi](https://github.com/sxyazi/yazi) terminal file manager and I can't get the arrow keys to work.

I thought I may need to remap them but I'm just not sure anymore. The arrow keys work out-of-the-box on WezTerm on yazi.

I'm in MacOS, latest version, M1 mac and Rio 0.0.18.

Any tips?

**Comment by raphamorim** [comment] 2023-09-14 13:12
Hey there @fdncred , thanks for the issue

Is all the keys (up,left,right and down) not working?

**Comment by fdncred** [comment] 2023-09-14 14:51
Correct. None of the arrow keys work for me unless I press cmd+arrow keys.

**Comment by raphamorim** [comment] 2023-09-15 21:05
yup I can reproduce. will look on it

**Comment by raphamorim** [comment] 2023-09-15 21:27
Ok found out the reason 🙈 
Since I could reproduce without any issues and I also could check the fix I will be closing it but please let me know anything.

Should be fixed in c71b6fc

**Closed by raphamorim** 2023-09-15 21:27 UTC
Labels: bug
