### ISSUE TITLE
Rio failing to draw blur upon launch

### ISSUE THREAD

**Issue by RaySlash** [raphamorim/rio#379] opened 2023-12-12 09:55 UTC
Hi reader,
Recently, I have been trying out rio and have been facing this issue where a new instance of rio fails to draw the window opacity and blur due to unknown reasons. I can help dig out more logs if that helps. My system is currently running NixOS `23.11.20231210.781e2a9 (Tapir)`. My configuration where rio is setup is [here](https://github.com/RaySlash/nixos-config/blob/32d3694eaa895ba246f94f319b9d6ef1e5dcfa3d/home-manager/frost/services.nix#L15C5-L86C11)

Output of `rio -V`:
```shell
rioterm 0.0.30
```
## Steps to reproduce
- Install rio from nixpkgs (I have tested v0.0.29 and v0.0.30)
- Use wayland compositor (I used Hyprland)
- Launch rio

## Logs and Information
Upon launching rio using `RIO_LOG_LEVEL=debug rio > debug_log-rio.txt`, my output is attached in file [debug_log-rio.txt](https://github.com/raphamorim/rio/files/13646344/debug_log-rio.txt)

![20231212_19h39m59s_grim](https://github.com/raphamorim/rio/assets/45141270/784a1516-24aa-495b-815d-7352464f770f)
After a quick inspection, I was able to find a line that could possibly be related to this. 
```shell
L24   [INFO] init::platform_impl::platform::wayland::window::state Blur manager unavailable, unable to change blur
```
## Temporary Workaround
I am able to draw blur on terminals that are spawned, if I make a change to the rio config and rebuild my system/home-manager or make changes to the rio `config.toml` which cause the spawned terminals to reload and show blur. I am uncertain if this is a NixOS specific issue or rio. Please note that new terminal instances still would not be able to draw blur. Please see the images attached where I rebuilt my system after changing the value to false for `disable-renderer-when-unfocused`:
![20231212_19h46m14s_grim](https://github.com/raphamorim/rio/assets/45141270/f036e59d-0fa8-47d9-a2cf-1a1dd22289ea)

 The startup-time and overall smoothness of the terminal is amazing. Any help is much appreciated. Thank you for being awsome.

**Comment by raphamorim** [comment] 2023-12-12 13:23
@RaySlash thanks for the issue,

Is only blur or the transparency isn't working either in the initialization?

**Comment by RaySlash** [comment] 2023-12-12 15:06
@raphamorim Both blur and transparency doesnt load on init. 😕

**Comment by raphamorim** [comment] 2023-12-12 15:10
hmm wonder if is connected to #361

**Comment by RaySlash** [comment] 2023-12-12 15:14
@raphamorim I saw it. but the fact that I am able to get it working like I have mentioned made me think otherwise.

**Comment by raphamorim** [comment] 2023-12-12 15:16
Yea, I will try to reproduce and spawn a new window on my linux at home to see if I can reproduce it.

**Comment by raphamorim** [comment] 2023-12-13 18:19
Tested quickly in an ubuntu and can't spawn with transparency neither blur 😢 

<img width="805" alt="Screenshot 2023-12-13 at 19 18 44" src="https://github.com/raphamorim/rio/assets/3630346/81c84001-0153-421f-87cf-5a67beb9cb80">

**Comment by RaySlash** [comment] 2023-12-13 19:30
Are you able to redraw blur and opacity upon changing and reloading the config for rio? Does that bring the transparency back for windows that are already spawned.

**Comment by RaySlash** [comment] 2023-12-13 20:20
I see https://github.com/raphamorim/rio/commit/f75e670b6e6c829b4ab4ce653a31f98d7ee7748c. 😇

**Comment by raphamorim** [comment] 2023-12-13 20:37
> I see https://github.com/raphamorim/rio/commit/f75e670b6e6c829b4ab4ce653a31f98d7ee7748c. 😇

Is this something you would like to use?

**Comment by RaySlash** [comment] 2023-12-15 02:01
@raphamorim Yes, love to see controp over decorations coming. Anyways, did you try to redraw blur to the terminal when u reload the config keeping at least one instance of rio open?

**Comment by AethanFoot** [comment] 2023-12-17 13:17
Just tried out rio on arch and have found the same issue of the opacity not loading on start, but drawing when the config is written to (dont need to change anything just save the file)

**Comment by raphamorim** [comment] 2023-12-17 13:42
> Just tried out rio on arch and have found the same issue of the opacity not loading on start, but drawing when the config is written to (dont need to change anything just save the file)

> @raphamorim Yes, love to see control over decorations coming. Anyways, did you try to redraw blur to the terminal when you reload the config keeping at least one instance of rio open?

I can confirm that if the file has updates, it get the transparency.

**Comment by raphamorim** [comment] 2023-12-17 16:48
@orhun could you confirm if update the configuration file would fix for you the transparency?

**Comment by lexpierce** [comment] 2023-12-17 17:22
I’ll reconfirm Monday, but on the latest MacOS if blur and transparency are active, the window is opaque at launch and saving the config file does NOT redraw transparency. If blur is off, the window is opaque on launch, but a config file save re-draws transparency.

**Comment by orhun** [comment] 2023-12-17 20:02
Wow, yeah, transparency works when I reload the config (save the file):

![rec_20231217T230112](https://github.com/raphamorim/rio/assets/24392180/02ea5b49-2644-4a83-b415-c967860d8234)

**Comment by raphamorim** [comment] 2023-12-17 20:56
> I’ll reconfirm Monday, but on the latest MacOS if blur and transparency are active, the window is opaque at launch and saving the config file does NOT redraw transparency. If blur is off but transparency is on, the window is opaque on launch, but a config file save re-draws transparency.

> so there are two issues here:

> blur breaks transparency
> Transparency isn’t recognized on initial window draw

A note: blur should break transparency, what blur does under the hood is create a blurred background (this is in other terminals as well).

However related to the issue you describer: What Rio doesn't do and prob is the reason is compute blur updates, so if you start the window with blur and wants to reset, it does not set blur off (might be a quick fix though)

**Comment by raphamorim** [comment] 2023-12-17 20:58
> Wow, yeah, transparency works when I reload the config (save the file):

Hmmm, very interesting will try something to see if corrects the behavior on linux

**Comment by lexpierce** [comment] 2023-12-18 01:14
> A note: blur should break transparency, what blur does under the hood is create a blurred background (this is in other terminals as well).
> 

Perhaps this is a UX issue then, as even if blur is somehow different to transparency, it doesn’t make logical sense to set blur on an opaque window.  Unless the setting was “background _image_ blur”, and not a general “background blur”, I would expect blur to blur the transparent background of the window (see WezTerm for an example), not the background image. Maybe the setting needs to be clarified?

**Comment by RaySlash** [comment] 2023-12-18 04:29
> I’ll reconfirm Monday, but on the latest MacOS if blur and transparency are active, the window is opaque at launch and saving the config file does NOT redraw transparency. If blur is off but transparency is on, the window is opaque on launch, but a config file save re-draws transparency.

I can confirm that the former condition is not true on Linux. Both blur and transparency are turned on for me and a hot reload of config does redraw both transparency and blur.

**Comment by raphamorim** [comment] 2023-12-18 08:35
Pushed a fix to force computation on first render after the window is created, tested locally and looks has fixed. Could anyone confirm it?

**Comment by raphamorim** [comment] 2023-12-18 08:36
> I can confirm that the former condition is not true on Linux. Both blur and transparency are turned on for me and a hot reload of config does redraw both transparency and blur.

Yea, windows/macos are the only stable apparently after the release. When I mean stable I talk about that at least you see the opacity off or blur if close and reopen the window

**Comment by orhun** [comment] 2023-12-18 11:01
Just tried `main` and unfortunately the fix didn't work for me - still had to save once to get transparency.

**Comment by lexpierce** [comment] 2023-12-18 18:44
ok, everything works as expected, aside from the transparency/blur on launch.  It is easier to just touch your config file, aka

`touch ~/.config/rio/config.toml`

than it is to open and save it. Linux and MacOS working as expected aside from the initial draw on launch.

**Comment by RaySlash** [comment] 2023-12-19 08:10
Hey, I can confirm that rio is currently drawing transparency and blur. I have tested out `main` branch's [fork](https://github.com/RaySlash/rio/tree/flakeify) as I'm writing this comment. The newly built rio binary launches with transparency and blur. Thank you!! ❤️ 

![20231219_18h08m53s_grim](https://github.com/raphamorim/rio/assets/45141270/358c7607-a5fb-4c2c-ba4c-2e784053c2ef)

**Comment by raphamorim** [comment] 2023-12-19 08:18
That's great! @RaySlash would you mind add that image you posted to the docs? https://raphamorim.io/rio/docs/configuration-file#using-blur-and-background-opacity

Closing this issue for now :D

**Closed by raphamorim** 2023-12-19 08:18 UTC

**Comment by RaySlash** [comment] 2023-12-19 08:47
Of course. Ill spin up a PR if you want me to. I believe you are talking about the last image I attached.

**Comment by raphamorim** [comment] 2023-12-19 09:08
> Of course. Ill spin up a PR if you want me to. I believe you are talking about the last image I attached.

Yes, that would be perfect. You have a beautiful setup :D
