### ISSUE TITLE
Control + Up/Down don't works as expected on neovim

### ISSUE THREAD

**Issue by AntonyZ89** [raphamorim/rio#371] opened 2023-12-08 18:06 UTC
On my neovim I use Control + up/down to select multiple lines with [Vim Visual Multi](https://github.com/mg979/vim-visual-multi) plugin.

Example using Alacritty/Kitty:
<p align="center">
<img width="49%" src="https://github.com/raphamorim/rio/assets/1340674/dcff75d2-e07f-40da-9b93-4b7e7816abab">
<img width="49%" src="https://github.com/raphamorim/rio/assets/1340674/92b830a2-00d3-4053-847e-c3a14f95d0a6" />
</p>

But on Rio Terminal, when I use Control + Up/Down arrow, it scroll my code. How to override/disable it? :)

Thank you.

**Comment by hougesen** [comment] 2023-12-10 19:34
I ran into the same issue after upgrading my version.

The default ansicodes sent when pressing `CTRL + ArrowKey` key was changed in v0.0.23.

| key               | v0.0.22 (11b0d4ea) | v0.0.23 (fcc9558c) |
| ----------------- | ------------------ | ------------------ |
| CTRL + UpArrow    | `^[[1;5A`          | `^[[1;4A`          |
| CTRL + DownArrow  | `^[[1;5B`          | `^[[1;4B`          |
| CTRL + RightArray | `^[[1;5C`          | `^[[1;4C`          |
| CTRL + LeftArrow  | `^[[1;5D`          | `^[[1;4D`          |

Enabling the [Kitty Keyboard protocol](https://raphamorim.io/rio/docs/configuration-file#enable-kitty-keyboard-protocol) "fixes" it for me. Sadly it seems that backspace is broken when Kitty is turned on 😅 (See #344 ).

As far as I can tell, `Ctrl + Shift + ArrowKey with Kitty false` sends the same code as `Ctrl + ArrowKey with Kitty true`.

**Comment by raphamorim** [comment] 2023-12-10 19:49
@hougesen @AntonyZ89 could check if latest main fixed the issue?

**Comment by hougesen** [comment] 2023-12-10 20:19
The newest commit has fixed it on my device (Ubuntu 23.10).

**Comment by raphamorim** [comment] 2023-12-10 20:36
Closing this issue for now since I can't reproduce anymore but let me know anything and I can reopen.

**Closed** 2023-12-10 20:37 UTC
