### ISSUE TITLE
render slow with fish

### ISSUE THREAD

**Issue by superiums** [raphamorim/rio#576] opened 2024-07-28 08:11 UTC
it works well with sh or bash, but very slow with fish.
even a `ls` command takes about 2-3 seconds.

**Comment by mervyn-mccreight** [comment] 2024-07-29 17:41
Can't reproduce that on my machine 🤔

I'm using fish as well (on MacOS) with `rioterm 0.1.3` and I can't see any differences performance wise to other shells.

Have you checked if `fish` runs smoothly in other terminals?

**Comment by avelino** [comment] 2024-08-02 01:10
I use fish and I'm not experiencing this slowness, it would be important to share more information 
- rio config
- fish config
- rio version

**Comment by superiums** [comment] 2024-08-08 13:02
rio --version
rioterm 0.1.1

os: both void-linux and arch . both slow.

rio config with default.
fish config:
```bash
if status is-interactive
    # if status is-login
    set -x VDPAU_DRIVER radeonsi
    # set -x OPENCV_LOG_LEVEL ERROR
    set -x PUPPETEER_EXECUTABLE_PATH /usr/bin/chromium
    set -x JAVA_HOME /usr/lib/jvm/default
    # set -x NODE_PATH "/opt/code/depot/node_global/lib/node_modules/"
    set -x NODE_PATH /opt/code/depot/node_global/pnpm_dir/5/node_modules
    set -x PNPM_HOME /opt/code/depot/node_global/pnpm_bin
    set -x SciTE_USERHOME ~/.config/scite
    set -x PATH $PATH $PNPM_HOME
    set -x PATH $PATH /opt/code/depot/node_global/bin/
    set -x PATH $PATH $JAVA_HOME/bin
    set -x PATH $PATH "$HOME/.local/bin"
    set -x V2RAY_LOCATION_ASSET /etc/v2ray
    set -x EDITOR /usr/bin/hx
    # set -x TERMINAL /usr/bin/foot #for mimeopen
    # set -x LF_DATA_HOME /tmp
    # set -x LF_BOOKMARK_PATH ~/.config/lf/
    abbr -a -g -- xi 'sudo xbps-install'
    abbr -a -g -- xup 'sudo xbps-install -Su'
    abbr -a -g -- xq 'xbps-query -s'
    abbr -a -g -- xs 'xbps-query -Rs'
    abbr -a -g -- xr 'sudo xbps-remove -R'
    ### ALIASES ###
    # navigation
    alias ..='cd ..'
    alias ...='cd ../..'
    alias .3='cd ../../..'
    alias .4='cd ../../../..'
    alias .5='cd ../../../../..'

    # ps
    alias psa="ps auxf"
    alias psgrep="ps aux | grep -v grep | grep -i -e VSZ -e"
    alias psmem='ps auxf | sort -nr -k 4'
    alias pscpu='ps auxf | sort -nr -k 3'

    # fzf

    set -x FZF_DEFAULT_COMMAND "fd --type f --exclude={.git,.vscode,node_modules,build}"
    # set -x FZF_DEFAULT_OPTS "--height 40% --preview 'highlight -O ansi -l {} 2>/dev/null'"
    set -x FZF_DEFAULT_OPTS "--height 40% --preview 'bat -n --color=always {}'"
    # set -x FZF_DEFAULT_OPTS "--height 40% --layout=reverse --preview '(highlight {} || cat {}) 2> /dev/null | head -500'"
    # alias fzfp="fzf --preview 'highlight -O ansi -l {} 2>/dev/null'"
    # z
    zoxide init fish | source

    # lesspipe
    set -x LESS -R
    set -x LESSOPEN '|/usr/bin/lesspipe.sh %s'
    set -x LESS_ADVANCED_PREPROCESSOR 1
    # set -x LESSCOLORIZER 'highlight -O ansi'
    set -x LESSCOLORIZE code2color

    # browser
    alias thorium='thorium-browser --disk-cache-dir=/tmp/thorium'
    alias chromium='chromium --disk-cache-dir=/tmp/chromium'


end

# bun
set --export BUN_INSTALL /opt/code/bun
set --export PATH $BUN_INSTALL/bin $PATH

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

```

**Comment by raphamorim** [comment] 2024-08-08 13:23
Thanks for the issue @superiums!

Are you using Rio with wayland?

**Comment by superiums** [comment] 2024-08-08 14:48
yes, with wayland. 
and amd gpu

**Comment by raphamorim** [comment] 2024-08-08 15:35
do you have x11 enabled as well to test? wondering if is an issue with rio wayland

**Comment by raphamorim** [comment] 2024-08-13 08:33
@superiums could you test again with v0.1.6?

**Comment by raphamorim** [comment] 2024-11-01 22:31
I am closing this issue for now since from v0.1.3 to v0.1.16 the renderer logic has positively suffered many updates in performances. Please lemme know anything and I can reopen it.

**Closed by raphamorim** 2024-11-01 22:31 UTC

**Comment by superiums** [comment] 2024-11-11 02:13
> @superiums could you test again with v0.1.6?

sorry for late.
i've tested it on Alpine, the problem has gone. 
my version is 0.1.7.
