### ISSUE TITLE
Rendering glitches caused by high color distribution

### ISSUE THREAD

**Issue by AnonymouX47** [raphamorim/rio#401] opened 2024-01-01 19:50 UTC
Some rendering glitches/artifacts occur when the FG/BG colors of cells are significantly diverse at reasonable font sizes, as seen in the following screenshot:

![Screenshot_2024-01-01_20-20-17](https://github.com/raphamorim/rio/assets/61663146/efe05810-072b-4d6d-9a64-82dacc67594f)

_Note: This is about the same font size as I normally use on other TEs._

This doesn't occur when the colors are less diverse (at the same font size):

![Screenshot_2024-01-01_20-23-59](https://github.com/raphamorim/rio/assets/61663146/75239e1c-414e-47f5-a2cd-97883087c8a5)

Also doesn't occur at greater font sizes:

![Screenshot_2024-01-01_20-25-27](https://github.com/raphamorim/rio/assets/61663146/6fce2979-e3f5-44fe-8a60-dee0a5c7178b)

_For context, these are image previews using a combination of upper and lower half blocks and blanks (spaces) with SGR **direct**-color FG and BG sequences. I was also able to reproduce this behavior using multiple image preview tools including those using different ranges of symbols._

Most likely related to #232 (though not sure, since no screenshots were provided) and maybe #356.

- - -

Though not related to this, I can't but notice the gaps between cells in the screenshots above.

- - -

OS: Manjaro
Window System: X
Window Manager: KWin
Desktop Environment: KDE
Rioterm Version: 0.0.33
Config: All default

Thanks so much for all your work on this project thus far and well done!

**Comment by raphamorim** [comment] 2024-01-22 16:56
Hey there @AnonymouX47 thanks for the issue and sorry for the delay,

Hmm wondering if the issue has been fixed in main, could you take a look?

**Comment by AnonymouX47** [comment] 2024-01-22 17:15
I noticed there are no nightly builds for linux distros. I'm not sure I currently have what it'd take to build from source. So, I'll probably wait for the next release or till I can build.

Thanks.

**Comment by raphamorim** [comment] 2024-07-28 20:03
I cannot reproduce it in 0.1.x releases, will be closing it for now but please let me know anything and I can reopen this issue 🙏

**Closed by raphamorim** 2024-07-28 20:03 UTC

**Comment by AnonymouX47** [comment] 2024-09-02 17:45
Fixed, thank you. :smiley:

Very sorry for the very late reply.
