### ISSUE TITLE
Color offset and color issues using Fira Code font

### ISSUE THREAD

**Issue by ehjmx** [raphamorim/rio#154] opened 2023-07-18 19:22 UTC
<img width="854" alt="Bildschirmfoto 2023-07-17 um 19 57 59" src="https://github.com/raphamorim/rio/assets/75489369/abbeca77-3361-459f-892e-d6564c59b9a3">
If you compare the above Fira Code to Victor Mono below
<img width="854" alt="Bildschirmfoto 2023-07-17 um 20 00 50" src="https://github.com/raphamorim/rio/assets/75489369/d566f813-d032-4305-a52a-8a2a20b73b62">
You can see that when a new powerline segment begins Fira Code has more offset and color issues than Victor Mono. 

_Originally posted by @ehjmx in https://github.com/raphamorim/rio/issues/135#issuecomment-1638628462_

**Comment by raphamorim** [comment] 2023-07-20 10:22
Hey @ehjmx can you check if it's still happening on 0.0.11?

**Comment by ehjmx** [comment] 2023-07-20 10:42
Hey @raphamorim better than before using Fira Code but still not as good as Victor Mono. I will post pictures later when I'm out of the office.

**Comment by ehjmx** [comment] 2023-07-20 18:19
Here are the pictures
Fira Code now shows "blocks" and the slash like slant only uses like 2/3 of the height
<img width="760" alt="image" src="https://github.com/raphamorim/rio/assets/75489369/f5412ef7-8f6d-4a72-92ae-83e8666a28c0">
Victor Mono does not show the blocks but is now consistent to Fira Code in only using 2/3 of the slant height
<img width="604" alt="image" src="https://github.com/raphamorim/rio/assets/75489369/d77f82fd-565e-40b2-8a6d-837885f9bcd1">

It's a step forward as both Fonts are now consistent in what they are displaying but it's also a step back in that the correct slant display for Victor Mono is now gone. 

For comparison that's how it looks in WezTerm using Fira Code. 
<img width="737" alt="image" src="https://github.com/raphamorim/rio/assets/75489369/df1d8868-f75f-4f21-bed1-0548d894c563">

**Comment by raphamorim** [comment] 2024-08-13 08:24
I think this was closed by v0.1.x release (cannot reproduce), will be closing it for now but I can reopen anything.

**Closed by raphamorim** 2024-08-13 08:24 UTC
Labels: bug
