### ISSUE TITLE
click on cursor to highlight seems to be one or two characters off

### ISSUE THREAD

**Issue by Jinkxed** [raphamorim/rio#182] opened 2023-08-15 18:28 UTC
When clicking to select and highlight on Mac OSX.  The actual highlighting starts one or two digits to the right of the cursor.

**Comment by Brianalmeida** [comment] 2023-08-19 13:56
I am seeing this too on Linux too

**Comment by raphamorim** [comment] 2023-08-25 10:08
woof, I can reproduce as well. marking as bug

**Comment by Brianalmeida** [comment] 2023-08-25 12:23
Using IBM Plex Mono, size 28

**Comment by raphamorim** [comment] 2023-08-25 13:08
And this is also applied whatever start to select text right?

**Comment by Jinkxed** [comment] 2023-08-25 13:14
Yup

**Comment by Brianalmeida** [comment] 2023-08-31 21:28
@raphamorim I noticed that the cursor highlighting is a bit better in the latest release

**Comment by raphamorim** [comment] 2023-09-14 08:24
@Brianalmeida @Jinkxed can you guys test in latest main?

**Comment by Brianalmeida** [comment] 2023-09-14 12:17
Compiling and testing now

**Comment by Jinkxed** [comment] 2023-09-14 12:49
Looking now.

**Comment by raphamorim** [comment] 2023-10-04 08:07
@Jinkxed @Brianalmeida could you try with latest main? (now is using fixed width for each cell)

**Comment by Jinkxed** [comment] 2023-10-04 11:48
Installed will play with it today and let ya know!

**Comment by Brianalmeida** [comment] 2023-10-08 12:24
@raphamorim just got back, so I'll give this another shot tomorrow morning and report back any findings

**Comment by Brianalmeida** [comment] 2023-10-09 13:43
@raphamorim using commitmono, the highlight looks good. IBM Plex Mono, and JetBrains Mono look good, too.

**Comment by fdncred** [comment] 2023-10-09 14:30
I just compiled the latest main on Windows and it seems worse now. It's 2 off instead of 1 off.

In the screenshot below, you can see my mouse selection cursor between the N and G in CHANGELOG.md. I started selecting a little bit to the right of the md and it didn't select the md and it seems to be 2 characters ahead to the left, as I drag from right to left.
![image](https://github.com/raphamorim/rio/assets/343840/e0a5ebe9-6742-4275-8427-737cd8621c17)

**Comment by raphamorim** [comment] 2023-10-09 15:59
hmmm, interesting @sztomi . I suppose you use `padding-x` equal to zero as well right?

**Comment by raphamorim** [comment] 2023-10-14 09:58
Basically rewrote the mouse position function for retrieve column on mouse position. Below you can see some examples, it's still not fully perfect but matches much better than was before

## Fira code, scale 1, padding 10, font-size 32px

![demo-selection-scale-1-padding-10-font-size-32](https://github.com/raphamorim/rio/assets/3630346/88b75262-9e9d-4b4b-b951-b30f1e06b664)

## Fira code, scale 2, padding 10, font size 32px

![selection-scale-2 0-padding-10](https://github.com/raphamorim/rio/assets/3630346/09c27261-b3a6-427a-b5bd-bc46701feef4)

## CascadiaMono, scale 1, padding 10, font size 18px

![demo-selection-scale-1-padding-10-font-size-18](https://github.com/raphamorim/rio/assets/3630346/8664ca4b-f272-49c1-95c6-63958570c159)

## Menlo, padding 0, scale 2, font size 23px

![demo-menlo-padding-0-scale-2 0-font-size-23](https://github.com/raphamorim/rio/assets/3630346/af3c6500-229f-4f5e-84b7-514047dc06fb)

## Victor Mono, padding 0, scale 1, font size 18px

![victor-mono-scale-1 0-padding-0-font-size-18](https://github.com/raphamorim/rio/assets/3630346/3be31d74-60d2-4164-93f5-e14511a909f4)

**Comment by raphamorim** [comment] 2023-10-14 10:05
Ok, figured out the glitch for scale 2.0 and pushed the correction.

**Comment by fdncred** [comment] 2023-10-14 12:27
Looks like a great improvement. When's the next release with this in it scheduled?

**Comment by raphamorim** [comment] 2023-10-14 16:28
> Looks like a great improvement. When's the next release with this in it scheduled?
Soon 🙈 😆 (just want to wrap up the VI mode and links for the next release before)

**Comment by tauil** [comment] 2023-10-16 08:59
I just tested now with the latest version in `main` (`9499076b7a80aa77d2d106abd5ab98bf16d9b815`).

It's better but still a bit off to me. Now it looks like the selection starts from the right edge of the character space/slot instead of left.

**Comment by Brianalmeida** [comment] 2023-10-18 13:46
The latest 0.0.23 release feels pretty accurate, in my testing so far

**Comment by raphamorim** [comment] 2023-10-18 13:52
> It's better but still a bit off to me. Now it looks like the selection starts from the right edge of the character space/slot instead of left.

Depending of the font and font-size used, the `floor()` logic affects negatively, is gonna be even better for next version (started to write tests to cover the corner cases) but the current logic should cover a lot of cases.

**Comment by Jinkxed** [comment] 2023-10-18 16:04
Can't wait to try it!

**Comment by tauil** [comment] 2023-10-19 14:10
It's fixed for me! 💯 Thanks!

**Comment by raphamorim** [comment] 2023-10-19 14:27
I will close this issue but I will be working on make it even more sharp for next versions. If you run into anything please feel free to create an issue :D

**Closed by raphamorim** 2023-10-19 14:27 UTC
Labels: bug
