### ISSUE TITLE
Rio ignoring config.toml on macOS 13.5.1

### ISSUE THREAD

**Issue by ehjmx** [raphamorim/rio#202] opened 2023-08-31 19:08 UTC
It seems as if Rio 0.0.18 is totally ignoring the configuration file config.toml.

It is placed unter ~/.config/rio/config.toml
![image](https://github.com/raphamorim/rio/assets/75489369/46f77e26-fde5-41c9-8ed7-679c6b95fd14)

The font used is definitely not Fira Code. I tried it as "firacode" "FiraCode" "Fira Code" in the new font config section it has no affect. 

The same goes for the Shell and Environment variables
shell = { program = "/opt/local/bin/bash", args = ["--login"] }
env-vars = ['SHELL=/opt/local/bin/bash']

Theme support seems to be broken as well as I see no difference in the appearance of Rio when setting or unsetting
theme =  "dracula"

What works is the font sitze.

While some of the settings where also ignored by 0.0.16 with the old config file format this is a huge step back and I was just about to use Rio as my every day terminal, now it seems to be back to Wezterm.

I attached my current config.toml as config.txt 
[config.txt](https://github.com/raphamorim/rio/files/12489401/config.txt)

Rio 0.0.18 and Canary - 8ebe062ed8b64bc49ae6868452c256ea488eaabf 
macOS 13.5.1
bash  5.2.15 installed via macports but /bin/bash that comes with macOS is also ignored
Font: Fira Code
Also tried Red Hat Mono, Victor Mono. Even Cascadia Mono out of the example for 0.0.17 doesn't seem to work.

**Comment by Brianalmeida** [comment] 2023-08-31 19:25
Would you mind sharing your config.toml file? 

There were some changes made to the config formatting in [0.0.17](https://github.com/raphamorim/rio/releases/tag/v0.0.17).

**Comment by ehjmx** [comment] 2023-08-31 20:07
Yes, I tried `/bin/bash` as well. 

> bash 5.2.15 installed via macports but **/bin/bash** that comes with macOS is also ignored

Thanks for the compatibility list. I didn't know that they have one. Fira Code was working as was Victor Mono even though Rio isn't on the list.

**Comment by ralgozino** [comment] 2023-09-01 09:09
I'm on macos and I use `Victor Mono`. It "works" but has some issues, I've also tested Fira Code, with the same result. It is a known issue and I believe Rapha is working on it.

Rio will ignore the configuration file if there's anything that it doesn't like (#168). I'd recommend trying to add one line at a time to the configuration file until you find which line is not working.

This is my fonts configuration:

```toml
[fonts]
[fonts.regular]
family = "Victor Mono"
style = "normal"
weight = 400
[fonts.bold]
family = "Victor Mono"
style = "bold"
weight = 800
[fonts.italic]
family = "Victor Mono"
style = "italic"
weight = 400
[fonts.bold-italic]
family = "Victor Mono"
style = "bold italic"
weight = 800
```

(using `Fira Code` instead of "Victor Mono" should also work)

**Comment by raphamorim** [comment] 2023-09-01 09:11
Yes, is exactly as @ralgozino mentioned.

I am working in a hint UI (connected to #168) so whenever rio fails to load a font it tells you why. One of the biggest reasons that could be failing 0.0.18 is that weight wasn't found (settled as 400 and found as 800) but the error is silent and is hard to figure out why today, so I think the #168 should be prioritized

**Comment by ehjmx** [comment] 2023-09-01 09:57
@ralgozino 
I used your configuration for Victor Mono and Rio still refuses to load the configuration file. I downloaded Victor Mono from 
https://rubjo.github.io/victor-mono/ and used otf as well as ttf 

If I don't use any setting for font Rio works as expected and reads the config.toml.

For now I have a workaround but it would be nice if I can switch back to Fira Code. I'm not that deep into fonts so how would I get the necessary information to put behind style or weight for Fira Code? Are they available in their documentation?

**Comment by ralgozino** [comment] 2023-09-01 10:39
> @ralgozino I used your configuration for Victor Mono and Rio still refuses to load the configuration file. I downloaded Victor Mono from https://rubjo.github.io/victor-mono/ and used otf as well as ttf
> 
> If I don't use any setting for font Rio works as expected and reads the config.toml.

I guess that there's something missing with the font that makes the configuration option fail.

I installed Victor Mono using the brew cask (the same for Fira Code). Have you tried that?

> For now I have a workaround but it would be nice if I can switch back to Fira Code. I'm not that deep into fonts so how would I get the necessary information to put behind style or weight for Fira Code? Are they available in their documentation?

This should work with `Fira Code`:

```toml
[fonts.regular]
family = "Fira Code"
style = "regular"
weight = 200
[fonts.bold]
family = "Fira Code"
style = "bold"
weight = 400
```

You can see the styles provided by the font in the macos "Font Bok" app, for example, I can see that in my case there's no style for italics available. I don't know about the weights, maybe in the Font's documentation? I'm not sure.

**Comment by raphamorim** [comment] 2023-09-01 10:48
If enable the logs with `RIO_LOG_LEVEL` or set in the configuration 
```
[developer]
log-level = "INFO"
```

it should show the reason (font not found or the weight wasn't found

**Comment by ehjmx** [comment] 2023-09-01 19:50
Where would I find the log? 

With
```
[fonts]
size = 16
[fonts.regular]
family = "Fira Code"
style = "Retina"
weight = 450
[fonts.bold]
family = "Fira Code"
style = "Bold"
weight = 600
```
Fira Code is detected and according to Font Forge and those [VS-Code Instructions](https://github.com/tonsky/FiraCode/wiki/VS-Code-Instructions) they are the correct weights.

If I comment those entries out I get the wrong font but everything else works as expected. 

Opening bash with `/opt/local/bin/bash --login` opens bash with the correct Fira Code etc.

**Comment by ehjmx** [comment] 2023-09-09 07:21
@ralgozino Indeed a new Rio instance opened when I ran `rio` from within /Applications/Rio.app/Contents/MacOS but sadly I get no output in the terminal be it rio, wezterm or Terminal.app that comes with macOS. 

In the meantime I tried with [CommitMono](https://github.com/eigilnikolajsen/commit-mono) whose weights etc are documented and followed the instructions given to add this font to Visual Studio Code but still Rio doesn't load bash. As soon as I comment out the font section bash is loaded. 

At the moment I leave the font section and start the bash with `/opt/local/bin/bash --login`

**Comment by raphamorim** [comment] 2023-09-09 07:24
Just a FYI: @ehjmx This problem in main should be not reproduceable anymore. For three reasons: 

- Now has an error UI that tells if the configuration file is invalid.
- I've migrated font-kit to fontdb. Would say that the font search "just" works if the weight isn't found will try to match somehow.
- (still wip) but I will connect font search results to the error UI as well.

**Comment by raphamorim** [comment] 2023-09-09 12:10
Added error alert for fonts as well <img width="712" alt="Screenshot 2023-09-09 at 14 09 39" src="https://github.com/raphamorim/rio/assets/3630346/0658a094-c33b-4ad3-b411-b89907418825">

**Comment by raphamorim** [comment] 2023-09-09 13:32
Latest main:

![error Ui](https://github.com/raphamorim/rio/assets/3630346/ce3943c5-3b43-4b31-b12d-4f68531c762f)

Closing this issue for now since will not be able to reproduce for next release, please let me know anything

**Closed by raphamorim** 2023-09-09 13:32 UTC
Labels: wishlist

**Comment by raphamorim** [comment] 2023-11-02 16:24
Hey @ehjmx I think had a regression with this the error UI functionality (isn't the firs time I heard it). Would you mind create an issue?
