### ISSUE TITLE
Windows 10 runtime error after using default configs

### ISSUE THREAD

**Issue by wewlad-dev** [raphamorim/rio#128] opened 2023-07-09 19:18 UTC
After Installation on Windows 10 x64, The installation didn't create a configuration file in the user folder. Copying the default configurations found here https://raphamorim.io/rio/docs/ and creating a new config.toml file in “C:\Users\USER\AppData\Local\rio\config.toml” will result in runtime error, error message attached.

Error text for google search in the future:

Rio: Runtime Error
panicked at 'Unable to spawn shell: The system cannot find the file specified. (os error 2)', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\teletypewriter-2.0.1\src\windows\conpty.rs:250:5

![Screenshot_3](https://github.com/raphamorim/rio/assets/59626410/b47c182b-004e-4940-b124-477c53db0665)

**Comment by KritR** [comment] 2023-07-09 20:49
I’d imagine this might be due to ConPty only being available on newer versions of Windows 10.

https://devblogs.microsoft.com/commandline/windows-command-line-introducing-the-windows-pseudo-console-conpty/

Could you confirm what version/build of Windows 10 you’re using?

**Comment by wewlad-dev** [comment] 2023-07-09 22:39
> I’d imagine this might be due to ConPty only being available on newer versions of Windows 10.
> 
> https://devblogs.microsoft.com/commandline/windows-command-line-introducing-the-windows-pseudo-console-conpty/
> 
> Could you confirm what version/build of Windows 10 you’re using?

Windows 10 Education, 22H2, OS build:19045.3155. Latest updates.

**Comment by KritR** [comment] 2023-07-10 08:44
Okay you’re on a new enough version of Windows that should include ConPty. 

I wonder if it’d got something to do with the default shell (powershell/cmd) not being in your path, which seemed to be an issue for other shells.

See
https://github.com/alacritty/alacritty/issues/3249

**Comment by raphamorim** [comment] 2023-07-10 09:02
Yes, the configuration file is never created when you install Rio and the terminal considers that the file doesn't exist. So is unlikely that's the root cause.

Also, looking the error message seems that ConPty can't spawn the powershell/cmd as @KritR mentioned. And yes, the Alacritty error looks the same as Rio. Considering that Rio crashes on initialization, would be good @wewlad-dev that you add the shell to the path before open Rio (https://stackoverflow.com/questions/714877/setting-windows-powershell-environment-variables).

There's a difference about Alacritty case though, they allow to configure shell by configuration file (1. maybe would be good to add this possibility to Rio as well) while Rio looks for the `SHELL` environment variable only and then falls back to `powershell` (2. maybe 
Rio fallback should be `cmd` instead)

**Comment by wewlad-dev** [comment] 2023-07-11 01:45
I'm honestly not following, my PowerShell is in the PATH, Rio does work with no issues too as long as I don't create that config file (or to be exact. using the default one, as it works fine if it's empty), that's my env path

`C:\Program Files\Rio\;C:\Program Files\Alacritty\;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\libnvvp;C:\Python311\Scripts\;C:\Python311\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\sniffnet\bin\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\Nsight Compute 2023.2.0\;C:\Program Files\Git\cmd;C:\Users\null\AppData\Local\Microsoft\WindowsApps;C:\Users\null\AppData\Roaming\npm`

Also, other terminal application works well like Alacritty, windows terminal, Cogno, etc.
So I assume that config file isn't correct?

**Comment by raphamorim** [comment] 2023-07-11 05:52
Hmmm, you do have `C:\Windows\system32\WindowsPowerShell\v1.0\` in the PATH, then it should have worked. Will look it further in my windows machine and reply here any finding.

**Comment by raphamorim** [comment] 2023-07-11 11:48
@wewlad-dev could you try with latest main?

I've added the possibility to define `shell` and `working_dir` in the configuration file.

<img width="856" alt="Screenshot 2023-07-11 at 13 47 32" src="https://github.com/raphamorim/rio/assets/3630346/1cd298fa-e09b-4999-b488-1d339c86fd01">

**Comment by raphamorim** [comment] 2023-07-14 17:34
Believe this PR https://github.com/raphamorim/rio/pull/144 add a conclusive fix for this scenario since can specify the bin as program, closing this issue but let me know anything.

**Closed by raphamorim** 2023-07-14 17:34 UTC
Labels: windows
