### ISSUE TITLE
Sugarloaf examples do not render correctly on Linux

### ISSUE THREAD

**Issue by Cthutu** [raphamorim/rio#50] opened 2023-05-25 12:50 UTC
I am using the latest Pop_OS! distribution and tried to run the sugarloaf example "text.rs".  I hit 2 issues:

* It render incorrectly:
![image](https://github.com/raphamorim/rio/assets/348614/bd4f54e8-ab22-4709-aaa6-876bc481c653)

* Maximising or resizing the window did not cause a redraw so the extra space was not rendered to.  This means on a tiling window manager, nothing was rendered at all (perhaps off window?).

**Comment by Cthutu** [comment] 2023-05-25 12:53
This is the result of the `rect.rs` example.  I am not sure if it's correct:
![image](https://github.com/raphamorim/rio/assets/348614/a617f4ce-d4d1-4879-8e4c-74eeb1a7eb56)

It also suffers from resizing problems.

**Comment by raphamorim** [comment] 2023-05-25 12:58
Hey there @Cthutu , yes I am aware (unfortunately). Same behaviour happens in the macos when having an external monitor with a scale factor different than 2.0. The initial render of sugarloaf has a hardcoded logic to start calculating layouts with 2.0, this need to be fixed.

Rect is the only case that's correct because doesn't the scale calculation.

**Comment by raphamorim** [comment] 2023-05-25 12:59
I plan to look on that soon, but feel free to send a PR as well 🙏

**Comment by raphamorim** [comment] 2023-05-25 13:05
BTW same happens to Rio in macos when using external monitor with 1.0 scale factor.

![image](https://github.com/raphamorim/rio/assets/3630346/f608f79e-8439-41c0-b3f3-c3aab0d882cd)

**Comment by raphamorim** [comment] 2023-05-25 19:58
Hey @Cthutu pushed a correction for those issues in 3b482ff526c66278b91318bcbbd73b789bddffe5. Please pull latest main and check if still happens.

I will close this issue after validate the fix with @filaruina

**Comment by Cthutu** [comment] 2023-05-26 07:45
Your changes fixes the first issue (woohoo!).  However, it doesn't render correctly on a tiled window manager (the window opens at the usual size then immediately gets resized and repositioned by the desktop manager) or when you resize the window (e.g. maximising).  I think this is just because you don't redraw on resize in the demo?  I haven't had enough time lately to get to the bottom of it.

**Comment by raphamorim** [comment] 2023-05-26 08:09
Yes, that's "expected" (not a bug) in demo since it only listen to ScaleFactor updates but is ignoring resize events without scale factor updates. Would be good to add it to the examples.

Also, I think it happens the same for rect case when happens a resize:

<img width="1392" alt="Screenshot 2023-05-26 at 09 59 53" src="https://github.com/raphamorim/rio/assets/3630346/b876a8ec-a7da-43c8-91f1-54d8c34b54ee">

For now I will close this issue but feel to update the examples 🙏 

Other thing to take in consideration is the examples are using fixed LogicalSize, idk how it behaves in Linux (considering test PhysicalSize instead)

**Closed by raphamorim** 2023-05-26 08:09 UTC
Labels: bug

**Comment by Cthutu** [comment] 2023-05-26 11:07
If you want pixel perfect you should be using PhysicalSize.  If you want to take into account the user's settings for monitor scale factors etc, LogicalSize is your friend.

**Comment by raphamorim** [comment] 2023-05-26 11:39
Yea, I like LogicalSize for the terminal as an user application but thinking in enable it as configuration option, then you can choose what fits better for your case.

**Comment by filaruina** [comment] 2023-05-26 11:48
> BTW same happens to Rio in macos when using external monitor with 1.0 scale factor.
> 
> ![image](https://user-images.githubusercontent.com/3630346/240921369-f608f79e-8439-41c0-b3f3-c3aab0d882cd.png)

This is fixed for me using main version. Running on ubuntu

**Comment by raphamorim** [comment] 2023-05-26 12:09
Great, thank you @filaruina for testing it too !
