### ISSUE TITLE
Option to hide title bar?

### ISSUE THREAD

**Issue by gaoDean** [raphamorim/rio#121] opened 2023-07-05 00:48 UTC
Self explanatory, like this: https://github.com/alacritty/alacritty/issues/168

**Comment by gaoDean** [comment] 2023-07-05 00:51
Window decorations in general would be nice, but i think this should be low priority

**Comment by raphamorim** [comment] 2023-07-05 05:31
Hey there @gaoDean thanks for the issue, nowadays macos is already have hidden title bar by default (I think you only can hid title bar in macos using winit), do you mean to add the option so people can activate it?

Regarding window transparency I think we have but I only implemented for wayland, would be great to have it for macos tbh.

**Comment by raphamorim** [comment] 2023-07-06 12:16
Closing this issue for now because it's already closed by default. But feel free to open another issue regarding the window decorations you would like to have. 👌

**Closed by raphamorim** 2023-07-06 12:16 UTC

**Comment by gaoDean** [comment] 2023-07-06 21:36
Hi @raphamorim, did you mean that the title bar is supposed to be hidden by default on macOS? When I downloaded it a few days ago it was still there?

**Comment by raphamorim** [comment] 2023-07-07 04:22
Yea it always was hidden, Rio never had visible title bar. In the windows configuration there’s a macro check (if macos then hide it)

**Comment by raphamorim** [comment] 2023-07-07 04:23
Unless you want it to show then Rio doesn’t have this option available for macos

**Comment by gaoDean** [comment] 2023-07-07 11:20
Hi @raphamorim, I just downloaded the newest build from a few hours ago, Rio hides *the window title* but not the *title bar*. I was asking if the window could look fullscreen, but act like a normal window. Also, do you also have the black bars on the top and bottom? Thanks


<img width="1920" alt="Screenshot 2023-07-07 at 9 20 05 pm" src="https://github.com/raphamorim/rio/assets/97860672/0b2589e4-1a01-4b83-96e1-20859b03ab0c">

**Comment by gaoDean** [comment] 2023-07-07 11:22
Even with decorations set to false (meaning title bar disabled), there are still the black bars. 

<img width="1920" alt="Screenshot 2023-07-07 at 9 21 50 pm" src="https://github.com/raphamorim/rio/assets/97860672/1936c2b7-de10-41a6-b90f-c4e6190f0eb0">

**Comment by raphamorim** [comment] 2023-07-07 11:57
Ahh now I got what you mean by title bar! :D 

So, when we talk about title bar is the native macos title bar, example below.

Terminal bar in terminal.app and alacritty:

<img width="463" alt="Screenshot 2023-07-07 at 13 51 43" src="https://github.com/raphamorim/rio/assets/3630346/ae13caee-82f8-4800-bbe7-dc7120599274">

<img width="354" alt="Screenshot 2023-07-07 at 13 52 08" src="https://github.com/raphamorim/rio/assets/3630346/a3f794c7-d29a-432a-b241-e499606d43ba">

But Rio and hyper terminal for example has it disabled by default:

![Screenshot 2023-07-07 at 13 54 21](https://github.com/raphamorim/rio/assets/3630346/4668e32c-a0d8-4a87-9c44-495627623a2f)

<img width="432" alt="Screenshot 2023-07-07 at 13 54 36" src="https://github.com/raphamorim/rio/assets/3630346/80118354-5272-4025-8651-c4c09df3a65c">

In your case, the problem is the background color isn't matching with the nvim/vim. Since Rio/Hyper renders with padding it gets visible, I would recommend use the same background color as your terminal if you want to get rid of that border. Rio and Hyper doesn't have adaptative mode so the border is always there when background changes, for example:

![Screenshot 2023-07-07 at 13 57 23](https://github.com/raphamorim/rio/assets/3630346/79819af5-680c-42a5-8125-b3fa1953d513)
<img width="482" alt="Screenshot 2023-07-07 at 13 57 37" src="https://github.com/raphamorim/rio/assets/3630346/e20da3f6-c1b5-4ed5-8487-301258102fc0">

**Comment by diocletiann** [comment] 2023-09-24 19:16
`winit::window::WindowBuilder::new().with_decorations(false)` should be all you need to get a clean window without decorations.

**Comment by raphamorim** [comment] 2023-09-24 19:18
@diocletiann is already configurable per configuration. Depends of navigation mode https://raphamorim.io/rio/docs/documentation/navigation and can show/hide the buttons too https://raphamorim.io/rio/docs/documentation/configuration-file

**Comment by diocletiann** [comment] 2023-09-24 19:22
I tried that but look at the border (and the rounded corners):

<img width="1512" alt="image" src="https://github.com/raphamorim/rio/assets/14058796/f6eb6b78-8116-4b86-9cf7-4ceb9fffbfd1">

**Comment by diocletiann** [comment] 2023-09-24 19:31
@raphamorim lighter theme looks worse:

<img width="1512" alt="image" src="https://github.com/raphamorim/rio/assets/14058796/8675027d-ac77-4f65-a384-7740bc2c453b">

Alacritty (and Kitty):
<img width="1512" alt="image" src="https://github.com/raphamorim/rio/assets/14058796/fdd3f1a6-0e90-415b-a23f-ee55aeccc012">

**Comment by yofriadi** [comment] 2024-02-24 08:52
could we also get this option in Windows, since Windows Terminal could achieve it
![image](https://github.com/raphamorim/rio/assets/24536844/78e595bf-f34c-4feb-9441-336c830c2c2e)

**Comment by raphamorim** [comment] 2024-02-24 10:05
@yofriadi you can disable decorations with `window.decorations = "Disabled` https://raphamorim.io/rio/docs/configuration-file#window

**Comment by yofriadi** [comment] 2024-02-24 11:01
is it in `Windowed` mode?
it is not worked for me in windowed mode with that config, here is my config
```
[window]
width = 1600
height = 1330
mode = "Windowed"
decorations = "Disabled"
```

**Comment by raphamorim** [comment] 2024-02-24 21:30
@yofriadi which version are you using? is the latest?

**Comment by yofriadi** [comment] 2024-02-24 23:54
yes, on latest, just downloaded it from releases.
