### ISSUE TITLE
rendering glitch

### ISSUE THREAD

**Issue by timhatch** [raphamorim/rio#436] opened 2024-01-28 14:33 UTC
I noticed an odd rendering glitch when testing the `koji` tool for formatting git commit messages (src: https://github.com/its-danny/koji/tree/main).

For some reason rio doesn't seem to correctly render the tickmark used to indicate progress through the message construction process. I've attached a screenshot which shows the progress status rendered from left to right in Rio, Alacritty and Terminal.app.

<img width="476" alt="Screenshot 2024-01-28 at 09 38 29" src="https://github.com/raphamorim/rio/assets/435261/d87e0497-2ff2-4ce6-ad65-e8fd6b7cd4c5">

It looks as though the "tick" is not being scaled properly in Rio?

Pls forgive the slight text colour differences, I've not spent time exactly matching the alacritty terminal theme to the rio defaults.

**Comment by ralgozino** [comment] 2024-01-29 08:30
probably a dupe of #135

**Comment by timhatch** [comment] 2024-01-29 09:54
Yes, that seems likely. Somehow I missed #338. I’ll close this, marking at as a duplicate

**Comment by timhatch** [comment] 2024-01-29 09:55
Duplicates #338

**Closed** 2024-01-29 09:55 UTC

**Comment by raphamorim** [comment] 2024-01-29 10:01
yes, duplicated 😢 . Should be gone after #428 work get merged
