### ISSUE TITLE
Box drawing issue with Berkeley Mono on MacOS

### ISSUE THREAD

**Issue by lexpierce** [raphamorim/rio#392] opened 2023-12-18 19:04 UTC
Haven't tested on Linux yet.

Here is an example from WezTerm with ligatures and other harfbuzz features off:

<img width="584" alt="Screenshot 2023-12-18 at 10 55 13 AM" src="https://github.com/raphamorim/rio/assets/5649235/772ce267-4c38-4c3f-8f78-88b4e980f15c">

and here is an example from iTerm 2 with ligatures on:

<img width="534" alt="Screenshot 2023-12-18 at 10 56 25 AM" src="https://github.com/raphamorim/rio/assets/5649235/7fcc070b-ce75-4b15-9361-747358884fb1">

and here is Rio 0.0.32:

<img width="540" alt="Screenshot 2023-12-18 at 10 56 53 AM" src="https://github.com/raphamorim/rio/assets/5649235/638d7604-59e4-47f5-8ec9-8eeb92178d91">

not sure if this is a unicode issue or a font rendering issue in sugarloaf.

**Comment by lexpierce** [comment] 2023-12-18 19:08
Works in Fira Code & PragmataPro. Crazy things happen in Monaspace *, including the already reported line clipping issue, but also box drawing goes off the rails.

**Comment by freijon** [comment] 2023-12-23 06:21
I have similar issues (though on Linux).
Please look at:

- the vertical lines (they are rendered as continuous vertical line in other terminals with the same font)
- the boxes aren't closed (see right corners of the boxes)

![20231222_21h20m13s_grim](https://github.com/raphamorim/rio/assets/1387831/c62245ae-063b-417e-a2be-b53f26b87071)

**Comment by raphamorim** [comment] 2024-06-10 14:22
These issues should not be able to reproduce with the latest release (v0.1.0) since the font processor was rewrote, closing this issue for now. In case find anything odd please let me know and we can reopen or create a new issue.

**Closed by raphamorim** 2024-06-10 14:22 UTC
