### ISSUE TITLE
Tab bar overlaps text

### ISSUE THREAD

**Issue by filipebarros** [raphamorim/rio#167] opened 2023-08-01 21:22 UTC
I'm not sure this is intended behaviour or if this is a bug though. 

Some of the configurations I am using:

```toml
font = "Hasklug Nerd Font Mono"
font-size = 14.0

padding-x = 10
```

<img width="1302" alt="image" src="https://github.com/raphamorim/rio/assets/748089/e5ba0e62-31e9-4c34-8763-89212f79953e">

On a different note, is there any plan to expand the existing custom keybinding actions to allow for something like `CMD` + `1` Switch to tab with index 1

**Comment by raphamorim** [comment] 2023-08-02 07:26
Hey @filipebarros can you open another issue about "On a different note, is there any plan to expand the existing custom keybinding actions to allow for something like CMD + 1 Switch to tab with index 1" (I am not sure if Rio will provide that by default keybinding but I can add an action to use in the custom keybindings so you can map it).

Regarding the text overlap looks same issue as Victor Mono and others like #154 , some fonts aren't working quite correctly in Rio.

**Comment by ralgozino** [comment] 2023-08-02 07:29
@raphamorim the same happens with the default font:
<img width="815" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/abba901d-23f6-4d67-9717-526958b16e92">

**Comment by ralgozino** [comment] 2023-08-02 07:37
Is not over the terminal text, but is over the window controls (the red, yellow and green dots for close, maximize and minimize are missing). Happens also using the BreadCrumb option:
<img width="984" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/5c2103a4-ba14-4bd8-976a-5024b9238cda">

**Comment by raphamorim** [comment] 2023-08-02 07:39
But that's another issue than text overlapping. Indeed is a bug, the toptab was supposed to be the one that deactivate the window buttons (not breadcrumb)

Can you check if everything is ok with bottom tag?

**Comment by ralgozino** [comment] 2023-08-02 07:52
I restarted Rio and now the controls are there, but overlap with the tabs:
<img width="713" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/5214f512-b586-4a5b-9576-a63ba9a50c47">

I guess that the controls disappearing was a glitch after testing the different options.

With BottomTab seems to be OK:
<img width="713" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/63e13337-ee16-4ad6-91e8-bd1c851891d3">

**Comment by ralgozino** [comment] 2023-08-02 08:19
Setting the mode to BreadCrumb and closing and reopening Rio, I lost the window controls again:
[Kapture 2023-08-02 at 10.15.06.webm](https://github.com/raphamorim/rio/assets/6362698/a619be85-17c6-452a-83dd-b9b18b544769)

Sorry for hijacking the issue, I can create another one if you prefer. I initially thought that was the same underlying problem as @filipebarros

**Comment by raphamorim** [comment] 2023-08-02 08:24
Yea, I can reproduce the Breadcrumb and I can confirm is a bug. Can you create an issue?
I think might be better remove this rule of TopBar and Breadcrumb and create a configuration property `hide-macos-window-controls` so doesn't get that much confusing.

**Comment by raphamorim** [comment] 2023-08-25 14:23
@filipebarros could you confirm if is still reproduce-able using latest main?

**Comment by filipebarros** [comment] 2023-08-25 23:13
Yes, it's still happening (didn't test with the nightly version though):

This is the bottom of the screen:
<img width="475" alt="image" src="https://github.com/raphamorim/rio/assets/748089/4c9d7516-2220-45b7-8cc5-04ba69d55d74">

**Comment by filipebarros** [comment] 2023-08-27 20:54
I just built from the main branch, and the issue is still present:

<img width="301" alt="image" src="https://github.com/raphamorim/rio/assets/748089/c35cc004-4b5c-426a-888e-ed4dd29f8a7d">

**Comment by bruisedsamurai** [comment] 2023-10-04 04:03
I am still getting it
![image](https://github.com/raphamorim/rio/assets/20334754/8eb33538-60f6-4f64-8dc5-c7414f480cd6)

**Comment by raphamorim** [comment] 2023-10-04 07:05
what's your font family @bruisedsamurai ?

**Comment by raphamorim** [comment] 2023-10-04 08:07
@filipebarros @bruisedsamurai  could you try with latest main? (now is using fixed width for each cell)

**Comment by bruisedsamurai** [comment] 2023-10-04 13:14
> what's your font family @bruisedsamurai ?

CaskaydiaCove Nerd Font



> @filipebarros @bruisedsamurai could you try with latest main? (now is using fixed width for each cell)

0.22 or latest main commit?

**Comment by filipebarros** [comment] 2023-10-04 19:34
Built from the latest main and I'm having issues opening the app:

```
Finished release [optimized] target(s) in 59.65s
"misc/rio.terminfo", line 101, col 23, terminal 'rio+base': Illegal character (expected alphanumeric or @%&*!#) - 'M-='
Created 'Rio.app' in 'target/release/osx'
mkdir -p release
cp -rf ./target/release/osx/* ./release/
cd ./release && zip -r ./macos-rio.zip ./*
  adding: Rio.app/ (stored 0%)
  adding: Rio.app/Contents/ (stored 0%)
  adding: Rio.app/Contents/_CodeSignature/ (stored 0%)
  adding: Rio.app/Contents/_CodeSignature/CodeResources (deflated 75%)
  adding: Rio.app/Contents/MacOS/ (stored 0%)
  adding: Rio.app/Contents/MacOS/rio (deflated 49%)
  adding: Rio.app/Contents/Resources/ (stored 0%)
  adding: Rio.app/Contents/Resources/rio.icns (deflated 8%)
  adding: Rio.app/Contents/Resources/72/ (stored 0%)
  adding: Rio.app/Contents/Resources/72/rio (deflated 50%)
  adding: Rio.app/Contents/Info.plist (deflated 83%)
```

When opening `Rio` it just hangs and eventually runs out of memory

**Comment by raphamorim** [comment] 2023-10-04 20:09
Thank you @filipebarros , yes I also was able to reproduce it locally 😓 I believe #259 should fix it but I was holding a bit to work on it but seems inevitable :D

**Comment by raphamorim** [comment] 2023-10-09 08:49
@filipebarros pushed one change that should have helped solving this bug, realized that sugaloaf was using font size instead of font bound height (which is the reason why fira code and cascadia code were working better than victor mono and some other fonts in terms of filling the lines correctly)

Where I can download the font you are using?

**Comment by filipebarros** [comment] 2023-10-09 18:42
I used homebrew for it. I'll build from scratch and try it out

**Comment by raphamorim** [comment] 2023-10-09 19:06
> I used homebrew for it.

I see, do you remember the formula name? (I want to reproduce locally)

**Comment by filipebarros** [comment] 2023-10-09 19:52
@raphamorim `font-hasklug-nerd-font`

**Comment by raphamorim** [comment] 2024-06-10 14:17
This issue should not be able to reproduce with the latest release (v0.1.0), closing this issue for now. In case find anything odd please let me know and we can reopen or create a new issue.

**Closed by raphamorim** 2024-06-10 14:17 UTC
Labels: bug
