### ISSUE TITLE
Feature request: cmd + click on links to open them in your browser

### ISSUE THREAD

**Issue by siimon** [raphamorim/rio#110] opened 2023-06-27 09:00 UTC
One feature I really miss from iterm is the possibility to cmd click links which then opens in your browser - would love if Rio had the same feature!

**Comment by avelino** [comment] 2023-06-28 07:11
Duplicate? #60

**Comment by raphamorim** [comment] 2023-07-03 14:56
Closing as duplicate of #60

**Closed by raphamorim** 2023-07-03 14:56 UTC
Labels: wishlist
