### ISSUE TITLE
Rio uninstalling itself after update prompt

### ISSUE THREAD

**Issue by tiagorangel1** [raphamorim/rio#829] opened 2024-12-01 13:47 UTC
For whatever reason, when the update prompt Rio appears, Rio gets uninstalled. I can't find it anywhere and `rio` in the terminal doesn't work, but when opening the deb again it says it's still installed. I have to properly uninstall it from that dialog and install it again.

## Steps to reproduce
1. Install rio for ubuntu via github releases
2. This shows up after a few minutes
![image](https://github.com/user-attachments/assets/f06d2607-7f2b-4a61-bd6f-6e316a401fa1)

3. you don't even need to click anything
5. Rio disappears from the taskbar and everywhere

```
tiago@tiago:~$ rio
bash: /usr/bin/rio: No such file or directory # rio disappears after the update prompt
```

```
tiago@tiago:~$ fastfetch
                            ....               tiago@tiago
              .',:clooo:  .:looooo:.           -----------
           .;looooooooc  .oooooooooo'          OS: Ubuntu oracular 24.10 x86_64
        .;looooool:,''.  :ooooooooooc          Host: <redacted>
       ;looool;.         'oooooooooo,          Kernel: Linux 6.11.0-9-generic
      ;clool'             .cooooooc.  ,,       Uptime: 18 hours, 31 mins
         ...                ......  .:oo,      Packages: 2535 (dpkg), 33 (flatpak), 32 (snap)
  .;clol:,.                        .loooo'     Shell: bash 5.2.32
 :ooooooooo,                        'ooool     Display (<redacted>): <redacted>
'ooooooooooo.                        loooo.    DE: GNOME 47.0
'ooooooooool                         coooo.    WM: Mutter (Wayland)
 ,loooooooc.                        .loooo.    WM Theme: Yaru-dark
   .,;;;'.                          ;ooooc     Theme: Yaru-dark [GTK2/3/4]
       ...                         ,ooool.     Icons: Yaru [GTK2/3/4]
    .cooooc.              ..',,'.  .cooo.      Font: Ubuntu Sans (11pt) [GTK2/3/4]
      ;ooooo:.           ;oooooooc.  :l.       Cursor: Yaru (24px)
       .coooooc,..      coooooooooo.           Terminal: rio 0.2.2 # this was copied when rio was still installed
         .:ooooooolc:. .ooooooooooo'           CPU: <redacted>
           .':loooooo;  ,oooooooooc            GPU: <redacted>
               ..';::c'  .;loooo:'             Memory: <redacted>
                                               Swap: <redacted>
                                               Disk (/): <redacted>
                                               Local IP (wlp2s0): <redacted>
                                               Battery: 100% [AC Connected]
                                               Locale: en_US.UTF-8


```

**Comment by raphamorim** [comment] 2024-12-05 21:59
Hey @tiagorangel1 thanks for the issue!

So weird, I cannot reproduce this on my ubuntu. How are you installing from GH releases?

**Comment by tiagorangel1** [comment] 2024-12-08 11:10
I used this link:

![image](https://github.com/user-attachments/assets/9c247b7b-1d60-4ad8-84be-c8e5eaa6ca63)

**Comment by raphamorim** [comment] 2024-12-08 16:16
Yea, I asked a friend to test on ubuntu and had similar result. He didn't get this issue before because he was building from the source.

I think migrate this to goreleaser should fix it cc @caarlos0

**Comment by raphamorim** [comment] 2024-12-08 16:33
Ah i get why it's broke (thanks to @caarlos0), rio package name needs to be fixed to rioterm

**Comment by raphamorim** [comment] 2024-12-08 16:48
Updated to rioterm https://github.com/raphamorim/rio/commit/d607d61eea4a8cee6116c075b93343c97aad90b0

**Comment by raphamorim** [comment] 2024-12-08 17:01
Should work now from next nightly versions https://github.com/raphamorim/rio/actions/runs/12223597341/job/34095330026

Closing this but please let me know anything and I can reopen

**Closed by raphamorim** 2024-12-08 17:01 UTC
