### ISSUE TITLE
If you run a long command or cat a long file and scroll up, hitting enter or down doesn't take you back to the command prompt.  You must scroll all the way back down.

### ISSUE THREAD

**Issue by chad-st** [raphamorim/rio#153] opened 2023-07-18 08:20 UTC

**Comment by raphamorim** [comment] 2023-07-18 08:26
hey @chad-st , thanks for the issue. Is that still happening in v0.0.9?

**Comment by Jinkxed** [comment] 2023-07-18 14:57
Hitting enter does indeed come back to the current prompt now in 0.0.9.  But it looks like another bug may have been introduced.  If you press up or down to scroll through history, it's inserting a new line and makes the current prompt unusable.

I was able to do this by: ssh into another server ( I didn't have this issue prior to 0.0.9 ).
- cat some large text file
- hitting enter to go back to the prompt
- then press up or down to go to previous command a couple times

If needed I can provide a video, but it basically inserts something like:

```
[user@some-remote-server ~]# cat /var/log/logstash/logstash-plain.log [user@some-remote-server ~]#                                          [user@some-remote-server ~]# cat /var/log/logstash/logstash-plain.log [user@some-remote-server ~]# exit                                     cat /var/log/logstash/logstash-plain.log [user@some-remote-server ~]#                                          [user@some-remote-server ~]#
[user@some-remote-server ~]# cat /var/log/logstash/logstash-plain.log [user@some-remote-server ~]# exit                                     cat /var/log/logstash/logstash-plain.log [user@some-remote-server ~]#                                          [user@some-remote-server ~]#
```

**Comment by ehjmx** [comment] 2023-07-18 19:20
I noticed something similar today where I have a long upload curl upload command. I will keep an eye on this as today was the first time I noticed this behavior and it only occurred when I used this command. 
Using a similar curl upload command to a different server which isn't that much shorter or even longer I didn't notice this behavior.

**Comment by raphamorim** [comment] 2023-07-20 19:17
Is possible to confirm this behaviour with v0.0.12?
I have made a cleanup in the key triggers that had some inconsistencies.

**Comment by raphamorim** [comment] 2023-07-21 19:46
I will be closing this issue for now since "If you run a long command or cat a long file and scroll up, hitting enter or down doesn't take you back to the command prompt. You must scroll all the way back down." is fixed, regarding the other bug if is it's confirmed that happens in 0.0.13 then we can open another issue (easier to lookup in history later)

**Closed by raphamorim** 2023-07-21 19:46 UTC

**Comment by ehjmx** [comment] 2023-07-22 05:30
I did ran a few of the longer commands with 0.0.13 and the issue seems to be resolved. Back at work on Monday I can do a thorough testing as I'm currently testing some api calls and how to proceed the output.
