### ISSUE TITLE
'rio' unknown terminal type

### ISSUE THREAD

**Issue by teroz** [raphamorim/rio#245] opened 2023-09-21 13:49 UTC
Hi there I love `rio` and pumped about the project. I do run into the above error when on ssh-ed to an ubuntu server.
I am running `rio`  v0.0.19 on Sonoma Preview
![Screenshot 2023-09-21 at 5 45 50 PM](https://github.com/raphamorim/rio/assets/853846/f065825c-9da7-4100-834c-a12866a2b89a)

**Comment by raphamorim** [comment] 2023-09-21 20:06
Hey there @teroz ,

Thank you for the issue. The problem is similar to https://github.com/raphamorim/rio/issues/216 and https://github.com/raphamorim/rio/issues/181.

Basically the issue is that your remote server doesn't have rio terminfo, which is why you're seeing this error. Locally echo $TERM should be rio but in the server that terminfo doesn't exist.

So you could install rio terminfo on a remote server or use a different terminfo either in config or per connection with env `TERM=xterm-256color ssh` could work.

Also related https://serverfault.com/questions/1098644/alacritty-throws-e558-terminal-entry-not-found-in-terminfo-when-running-htop

I am closing this issue regarding rio terminal info but let me know anything.

**Closed by raphamorim** 2023-09-21 20:06 UTC
