### ISSUE TITLE
Background color not entirely set on vim

### ISSUE THREAD

**Issue by matheus1lva** [raphamorim/rio#88] opened 2023-06-07 13:00 UTC
![image](https://github.com/raphamorim/rio/assets/831308/c1072707-3c88-43f9-970b-a4bbd2076a0d)
Currently using catpuccin theme and it isnt filling the whole window. I saw we have #52 already, but not sure if it was released yet. Just pinging to track it!

**Comment by matheus1lva** [comment] 2023-06-07 13:13
As also discussed on twitter, the font even though is set to 16, isnt being applied correctly. My conf is:

```
[style]
font = "SpaceMono Nerd Font"
font-size = 16
```

**Comment by raphamorim** [comment] 2023-06-07 18:30
The background color not being set isn't an issue because Rio decoratively has borders, so with a VIM background different than Rio would look like this: 

![image](https://github.com/raphamorim/rio/assets/3630346/3e49fef9-abdd-4ad6-9cad-e8589951e9b8)

The problem is that using custom fonts, it does look often quite small compared to original.

**Comment by raphamorim** [comment] 2023-06-07 18:33
This issue is connected to the same behaviour described in https://github.com/raphamorim/rio/issues/80#issuecomment-1577286534

The borders aren't the issue, hyper also does the same:

<img width="1060" alt="Screenshot 2023-06-07 at 20 32 23" src="https://github.com/raphamorim/rio/assets/3630346/bdb3a5cd-5feb-4fd1-9ea3-df46ab1a1635">

But should be able to fit the screen at least and as you mentioned font-size should have been increasing it. Added bug label and wishlist.

**Comment by OlshaMB** [comment] 2023-06-14 17:46
## Fira Code
<img width="1880" alt="Снимок экрана 2023-06-14 в 20 40 58" src="https://github.com/raphamorim/rio/assets/68439653/9c92f81e-9d7b-42d7-b3d0-a2668051f0f4">

## JetBrains Mono
<img width="1880" alt="Снимок экрана 2023-06-14 в 20 44 19" src="https://github.com/raphamorim/rio/assets/68439653/3ff9cae4-4765-4620-abec-387b65d24349">

**Comment by raphamorim** [comment] 2023-06-14 17:48
woof, thank you @OlshaMB 🙏

**Comment by raphamorim** [comment] 2023-06-20 09:47
@OlshaMB @matheus1lva would mind test with latest main?

**Comment by raphamorim** [comment] 2023-06-25 06:44
I will be closing this issue since not able to reproduce in v0.0.7, please let me know anything and we can reopen in case.

**Closed by raphamorim** 2023-06-25 06:44 UTC
Labels: bug
