### ISSUE TITLE
Cursor shape isn't restored

### ISSUE THREAD

**Issue by GaspardCulis** [raphamorim/rio#279] opened 2023-10-10 09:34 UTC
### Issue 

If I change my cursor shape to a pipe for example
```toml
# ~/.config/rio/config.toml
cursor = '|'
```
And then launch a process that changes the cursor's shape like a CLI text editor (vim or helix), when I exit the process the cursor shape does not get restored to the one defined in config.toml.

### Expected behavior

The cursor shape should get restored to the one defined in the config.

Something like xfce4-terminal has the expected behavior.

#### Rio:
```
❯ rio --version
rioterm 0.0.22
```

#### OS:

```
❯ cat /etc/os-release
NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch btw"
BUILD_ID="2023.05.28"
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"
❯ uname -r
6.5.6-zen2-1-zen
```

**Comment by raphamorim** [comment] 2023-10-10 16:39
Hey @GaspardCulis thanks for the issue,

It always lead to back to Block right? (It is hardcoded in the term logic as the default) will mark to take a look.

**Comment by raphamorim** [comment] 2023-10-12 08:58
Fixed in the main

![fix-cursor](https://github.com/raphamorim/rio/assets/3630346/0b2c090b-46a8-4276-9e67-5fda6cc25464)

**Closed by raphamorim** 2023-10-12 08:58 UTC
Labels: bug

**Comment by vinoff** [comment] 2024-12-30 09:18
I am having this issue:

Steps to reproduce:

- open vim
- enter insert mode (via `i` or `a`)
- cursor does not change to input mode cursor. It stays a block when it should be a vertical line.

If you move the cursor around, it changes to the vertical line.

The opposite also happens, that is, if you are in insert mode and switch to normal mode, the cursor does not change to block until you move the cursor around.


Interestingly, if you enter insert mode via "`o`", the cursor behaves correctly. Probably because it changes position automatically.

I am using rioterm 0.2.2.

**Comment by raphamorim** [comment] 2024-12-30 14:23
Hey @vinoff could you create a different issue? (using same text)

I feat this issue context has become too long for me to even keep track 🙏
