### ISSUE TITLE
LS command shows file list with unaligned columns

### ISSUE THREAD

**Issue by jeffrbrito-nent** [raphamorim/rio#56] opened 2023-05-26 10:43 UTC
<img width="1203" alt="image" src="https://github.com/raphamorim/rio/assets/74405713/b4d00fe4-89d9-44d0-ba66-af5bb125cbee">

**Comment by niuez** [comment] 2023-06-03 05:11
It seems to be caused by rendering tab character `\t`. It can be fixed with replacing `\t` to single space ` `.
I tried fixing it in `create_sugar()`, And it seems to work.
```rust
Sugar {
    content: if square.c == '\t' { ' ' } else { square.c },
    foreground_color,
    background_color,
    style,
    decoration: None,
}
```
There are problems...
- I don't know why it breaks when rendering `\t`...
- If this issue will be fixed by replacing, I don't know where in the code this should be corrected.

before 
<img width="1209" alt="image" src="https://github.com/raphamorim/rio/assets/30189186/b3085b2c-4974-4eb2-825b-d8475334153f">
after
<img width="1350" alt="image" src="https://github.com/raphamorim/rio/assets/30189186/d5ba5daa-5892-4e0b-9a18-35881e58835b">

**Comment by raphamorim** [comment] 2023-06-03 05:22
Good finding @niuez ,

Yes that make fully sense in my head why is failing, looked even how alacritty does and they also replace for `' '` https://github.com/alacritty/alacritty/blob/4b92388396c6da783809c7ce511b5cf6be8a0624/alacritty/src/renderer/text/mod.rs#L150C1-L153

```rust
fn draw_cell(
        &mut self,
        mut cell: RenderableCell,
        glyph_cache: &mut GlyphCache,
        size_info: &SizeInfo,
    ) {
        // Get font key for cell.
        let font_key = match cell.flags & Flags::BOLD_ITALIC {
            Flags::BOLD_ITALIC => glyph_cache.bold_italic_key,
            Flags::ITALIC => glyph_cache.italic_key,
            Flags::BOLD => glyph_cache.bold_key,
            _ => glyph_cache.font_key,
        };

        // Ignore hidden cells and render tabs as spaces to prevent font issues.
        let hidden = cell.flags.contains(Flags::HIDDEN);
        if cell.character == '\t' || hidden {
            cell.character = ' ';
        }
```

Would you mind adding a fix for it? You can add this logic in `create_sugar` since is our translation to the renderer.

**Comment by raphamorim** [comment] 2023-06-03 06:26
Cannot reproduce anymore, closing this issue. <img width="682" alt="Screenshot 2023-06-03 at 08 26 32" src="https://github.com/raphamorim/rio/assets/3630346/32cb1120-5d90-48a0-8341-f0a2f5033b73">

**Closed by raphamorim** 2023-06-03 06:26 UTC
Labels: bug
