### ISSUE TITLE
Font rendering glitch on Intel HD520 graphics

### ISSUE THREAD

**Issue by DanielTolentino** [raphamorim/rio#120] opened 2023-07-04 17:25 UTC
The font displays glitches and overlaps with other characters when using Powershell and WSL on Windows.
Default font and configs.

![image](https://github.com/raphamorim/rio/assets/5665358/23710efd-300d-4676-a0c6-9e5a4820656e)

https://github.com/raphamorim/rio/assets/5665358/e835942a-3e14-4a3d-ab8e-99108e8a16bd

**Comment by raphamorim** [comment] 2023-07-04 17:28
wow, thanks for the issue @DanielTolentino, are you using any custom font or is the default?
Also, do you know if you are using DX11, DX12 or Vulkan?

**Comment by DanielTolentino** [comment] 2023-07-04 17:31
Sorry for the missing infos. It's the default font and default configs, clean installation. My system is on DX12, but I don't know how to check what Rios is using right now.

**Comment by raphamorim** [comment] 2023-07-04 17:33
No worries, you provided all information I asked in the first question. Thank you

**Comment by DanielTolentino** [comment] 2023-07-04 17:35
Here's the DxDiag of my system
https://gist.github.com/DanielTolentino/7eedbf23347b51c79fc1b157a1cf5f0f

**Comment by raphamorim** [comment] 2023-07-04 19:56
@DanielTolentino can you try to reproduce using `performance = "Low"` as config ?

(You can read more about config file in https://raphamorim.io/rio/docs/#configuration-file)

**Comment by DanielTolentino** [comment] 2023-07-04 20:10
Yes, low:
![image](https://github.com/raphamorim/rio/assets/5665358/e3dcc2f7-3818-440e-8ca4-43cad6f834b4)

**Comment by raphamorim** [comment] 2023-07-04 20:12
Hmm thank you for the screenshot. That's very interesting, I wonder if is a driver bug. Will look on it and update this issue if I get more information, please feel free to do the same.

**Comment by DanielTolentino** [comment] 2023-07-04 20:20
Yep, the font rendering glitch seems to be specific to systems using the Intel HD520 graphics. Just tested on a system with a nvidia GPU, no glitches at all. Maybe we can update the issue title to highlight that this issue is affecting Intel HD520 graphics for now.

**Comment by raphamorim** [comment] 2023-07-04 20:21
> Yep, the font rendering glitch seems to be specific to systems using the Intel HD520 graphics. Just tested on a system with a nvidia GPU, no glitches at all. Maybe we can update the issue title to highlight that this issue is affecting Intel HD520 graphics for now.

Updated the title 👍

**Comment by raphamorim** [comment] 2023-07-04 20:38
@DanielTolentino if you are keen to contribute, would you mind update the https://raphamorim.io/rio/install/#windows section by adding more information about how to install on Windows? I feel the information there is pretty poor (for example is missing details about click "Keep" after download the installation file)

Would also be great add info about how switch drivers on Windows.

**Comment by DanielTolentino** [comment] 2023-07-04 21:19
I would love to contribute, I was already drafting some topics about Rio on Windows, like changing the default shell to the new PowerShell platform (pretty easy btw). I'll be working on this, thanks!

**Comment by raphamorim** [comment] 2023-07-20 10:44
Just to confirm @DanielTolentino , is this still happening in 0.0.11?

**Comment by DanielTolentino** [comment] 2023-07-20 13:37
Oh, I moved to linux on the laptop, I'll find a way to test it again on Windows.
Sorry 😞

**Comment by raphamorim** [comment] 2023-07-21 06:55
Tested in few Windows machine with DX12 not able to reproduce anymore. Closing this issue for now 🙏

**Closed by raphamorim** 2023-07-21 06:55 UTC
Labels: bug, windows
