### ISSUE TITLE
Cursor blinking is triggered by changes in inactive tabs

### ISSUE THREAD

**Issue by hougesen** [raphamorim/rio#437] opened 2024-01-28 15:37 UTC
Changes in other tabs should not cause the active tab to rerender since it makes the ui seem buggy.  

[Screencast from 2024-01-28 16-23-43.webm](https://github.com/raphamorim/rio/assets/56034786/46bf027b-16bd-4d04-9ac8-6f94d1702668)

**Comment by hougesen** [comment] 2024-01-28 15:42
Resizing the window also triggers a lot of rerenders.

[Screencast from 2024-01-28 16-40-10.webm](https://github.com/raphamorim/rio/assets/56034786/285dd7dc-b99e-40b1-9618-e9d8ec74d08b)

**Comment by raphamorim** [comment] 2024-01-28 19:01
Good findings, yes those behaviors should be fixed. Now cursor can come either from terminal and state, most of times comes from state, but would be good move part of cursor rendering logic outside of state (state reflects in the current window rendering state).

**Comment by hougesen** [comment] 2024-01-28 23:06
Are the changes required affected by #428?

I also noticed selecting text is a lot slower when `blinking-cursor` is turned on.

Turned off:

[Screencast from 2024-01-28 23-58-52.webm](https://github.com/raphamorim/rio/assets/56034786/8de64294-c7cd-47c9-9572-2e905e1f50bb)

Turned on:

[Screencast from 2024-01-28 23-59-41.webm](https://github.com/raphamorim/rio/assets/56034786/0ae43942-94db-4bbc-acd0-89df39990ee3)

It is not a problem when using nvim or zellij, which I am guessing is because they handle cursor state themself (?).

**Comment by raphamorim** [comment] 2024-01-29 16:03
> Are the changes required affected by https://github.com/raphamorim/rio/pull/428?

No shouldn't be affected, #428 should touch mostly sugarloaf crate.

> I also noticed selecting text is a lot slower when blinking-cursor is turned on.

Hmm, that would make sense because is stacking rendering and blinking (rendering) in the same time.

> Adding a check for whether there is a selection eliminates the delay after first render.

I like the solution for now but shouldn't be the final fix (I guess) because could be that users would expect the cursor to blink if have selected text (?? not sure tbh).

Would you mind create a PR with those changes?

**Comment by hougesen** [comment] 2024-01-29 23:13
Sure, coming up.

**Comment by hougesen** [comment] 2024-06-11 13:57
Sadly this was not fixed as a by product of `v0.1.0` 😭

**Comment by raphamorim** [comment] 2024-08-03 12:33
@hougesen is this happening still right? I've tried to reproduce locally without success. Is your configuration for cursor blinking true?

**Comment by raphamorim** [comment] 2024-08-03 13:08
I've pushed a change to main, I think it should fix this issue (and also improve the overall experience for tabs) could you take a look later? 🙏

**Closed** 2024-08-07 12:45 UTC
Labels: wishlist
