### ISSUE TITLE
Window output lost when rio loses focus

### ISSUE THREAD

**Issue by countfloyd** [raphamorim/rio#706] opened 2024-10-13 16:48 UTC
If I run a shell command that takes a while to complete and switch away from the rio window while it's running, upon switching back, the remaining output from the shell command is not showing, even though the command has completed. Pressing enter will catch up and show the remaining output along with the shell prompt.

As an example, try running this command:
```
for ((a=1; a <= 10 ; a++))
do
   echo $a
   sleep 1
done
```

Switch away from the rio window while this is running a switch back after about 10 seconds. The output from the completed command does not show until you press enter (or return)

**Comment by raphamorim** [comment] 2024-10-22 21:28
Hey @countfloyd thanks for the issue,

Could you share your version and configuration file? I've tried to reproduce locally but couldn't have any success.

**Comment by countfloyd** [comment] 2024-10-22 21:34
Sure! Using version 0.1.17. Attaching my configuration. Had to change extension to .txt so GitHub would let me attach.

[config.txt](https://github.com/user-attachments/files/17482302/config.txt)

**Comment by raphamorim** [comment] 2024-11-01 21:52
Sorry for the late reply, I couldn't find anything "weird" on config. Could you try with a nightly build or from main? Otherwise I will try to debug again

Are you running on an external monitor?

**Comment by countfloyd** [comment] 2024-11-01 21:56
Yes, I can try a nightly version and let you know. I find it happens quite reliably when I start a long-running command and switch away from the rio window. When I switch back, the command has finished but the text showing Is still at the point where I switched away. I am running on a Mac Studio, which doesn't have a built-in monitor so yes, I'm running on an external monitor connected via USB-C.

**Comment by countfloyd** [comment] 2024-11-01 22:25
Just tried the latest HEAD and it seems to have resolved the issue.

**Comment by raphamorim** [comment] 2024-11-01 22:28
That's great, could be because I removed the logic regarding unfocused render on 0.1.16, I decided to put back on main few weeks ago.

Well, for now I will close this issue, however if you run into this issue again on 0.2.0 I definitely can reopen. Thanks for the issue :D

**Closed by raphamorim** 2024-11-01 22:28 UTC
