### ISSUE TITLE
Scrollbar feature request

### ISSUE THREAD

**Issue by bfstree** [raphamorim/rio#421] opened 2024-01-19 17:19 UTC
I sometimes have huge (100K~1M lines) stdout output. The default macOS terminal has a scrollbar, which I can use to quickly skim through some of the lines. In addition, I can visually check the approximate location of the scrollback buffer I am reading.

Some might say redirect the output to a file and check/search using an editor, but I just need a quick glimpse, among multiple frequent executions. Thus, this method is a hassle. I also don't have the exact line number information where I need to look at, since the stdout result fluctuates each execution.

Using the default macOS terminal's scrollbar can let me quickly visualize the status of the scrollback buffer.
I hope Rio can also have a scrollbar. (Maybe it appears only when scrolling back? & Have an option to enable/disable) Thanks!

**Comment by flba-eb** [comment] 2024-01-22 14:17
Is this a duplicate of https://github.com/raphamorim/rio/issues/304?

**Comment by raphamorim** [comment] 2024-01-22 16:50
I want and would love to start to work on the scrollbar support (as something optional) but haven't started it yet and currently focusing on fix some long known issues with font rendering. If anyone is interested on work on it please feel free to do 🙏 

> Is this a duplicate of https://github.com/raphamorim/rio/issues/304?

Yes, thank you @flba-eb . Closing this one as duplicate.

**Closed by raphamorim** 2024-01-22 16:50 UTC
