### ISSUE TITLE
[Distribution] brew doesn't install the application

### ISSUE THREAD

**Issue by MrPandir** [raphamorim/rio#537] opened 2024-06-11 09:41 UTC
If you install rio using:
```zsh
brew install --cask rio
```
Homebrew will install rio, you can run it through the terminal using `rio`. But it won't create the program in the `Applications` directory, you won't be able to launch Rio via Launchpad or via Spotlight.

P.S. I don’t exclude the possibility that my Homebrew is broken 😅

**Comment by raphamorim** [comment] 2024-06-12 08:51
Hey @MrPandir thanks for the issue!

Hmmm, I cannot reproduce it tbh, but if this is happening then is an issue on homebrew because Rio isn't responsible for installation process with brew. Will close it for now but let me know anything :D

**Closed by raphamorim** 2024-06-12 08:51 UTC
