### ISSUE TITLE
`shift+arrows` doesn't work on macOS (rio v0.0.22)

### ISSUE THREAD

**Issue by 4thwithme** [raphamorim/rio#269] opened 2023-10-03 11:04 UTC
When I'm trying to select text with `shift + arrow` in nvim -> it doesn't happen.

I expect smth similar to iTerm behavior

it worked before in rio
<img width="257" alt="Screenshot 2023-10-03 at 12 58 17" src="https://github.com/raphamorim/rio/assets/42321105/0e001518-439e-4882-ad23-efab671f6156">

Rio v 0.0.22
<img width="255" alt="Screenshot 2023-10-03 at 12 59 42" src="https://github.com/raphamorim/rio/assets/42321105/63b274ba-70fa-42d2-a622-82e425f98b46">

**Comment by 4thwithme** [comment] 2023-10-03 12:40
Hi @raphamorim!

I just removed my latest version and installed 0.0.16 and it works there

**Comment by raphamorim** [comment] 2023-10-03 12:53
ah I see, I have an idea of what's the reason, what happens when you do an `echo $TERM`?

**Comment by 4thwithme** [comment] 2023-10-03 13:01
It says `xterm-256color`

**Comment by 4thwithme** [comment] 2023-10-03 14:13
I found out that it works with `command + shift + arrow`

**Comment by raphamorim** [comment] 2023-10-03 16:23
I believe it should be working with shift + arrow, probably I broke something in the 0.0.18 when I ported the kitty keyboard protocol.
How have you installed rio? using homebrew?

**Comment by 4thwithme** [comment] 2023-10-03 16:25
yep, using `brew`

**Comment by raphamorim** [comment] 2023-10-03 16:27
hmmm, because it should have been installed the terminfo as well
```shell
echo $TERM
rio
```

**Comment by raphamorim** [comment] 2023-10-03 16:28
did you install by cask or formula?
```
brew install --cask rio
```
or
```
brew install rio
```

**Comment by raphamorim** [comment] 2023-10-03 16:28
I think only cask install the terminfo https://raphamorim.io/rio/docs/install/terminfo

**Comment by 4thwithme** [comment] 2023-10-03 16:38
I used 
brew install --cask rio

**Comment by 4thwithme** [comment] 2023-10-03 16:46
It says I have terminfo

<img width="1159" alt="Screenshot 2023-10-03 at 6 43 06 PM" src="https://github.com/raphamorim/rio/assets/42321105/55495455-9b33-4d38-ae29-2f20f7e3df92">

Also after last installation with
`brew install --cask rio`

I got 
```
echo $TERM
rio
```

only `command + shift + arrow` works

**Comment by raphamorim** [comment] 2023-10-03 16:56
ok that's great to know :D 

will look on it during this week

**Comment by raphamorim** [comment] 2023-10-17 14:45
@4thwithme could check with latest main?

**Comment by raphamorim** [comment] 2023-10-21 07:40
I am closing this one since looks connected to #53 and now that rio has returned to legacy (0.0.23) instead of kitty keyboard protocol, I cannot reproduce anymore. Please let me know anything 🙏

**Closed by raphamorim** 2023-10-21 07:40 UTC
