### ISSUE TITLE
Rio keeps latent image when switching from another desktop

### ISSUE THREAD

**Issue by 0x5c** [raphamorim/rio#175] opened 2023-08-03 21:46 UTC
When switching from a desktop to one where a rio window exists, the image of the previous desktop is kept by the rio window, until it receives a click or key event.

![image](https://github.com/raphamorim/rio/assets/5877043/d40995f7-c3a6-448d-a75a-d263e77e1d0d)

^My browser showing the rio repository, except it's a latent image in the rio window

This reproduces systematically without fail on my system.

### System
Rio is 0.0.16 with the default config (no config file)
The WM is awesomewm 4.3 (X11), with picom 10.2, on Voidlinux

**Comment by raphamorim** [comment] 2023-08-25 14:22
Wow that's quite weird tbh. 

Just to confirm to see if I understood correctly, whenever you switch windows, Rio keeps the content of the previous window?

**Comment by 0x5c** [comment] 2023-08-26 01:14
> Just to confirm to see if I understood correctly, whenever you switch windows, Rio keeps the content of the previous window?

It only happens when switching desktops (aka "workspaces" in some DEs). Window switching is unaffected.

**Comment by raphamorim** [comment] 2023-09-11 11:48
I simply can't reproduce it in the 0.0.18, I will be closing this one but if anyone finds out or can reproduce I will reopen.

**Closed by raphamorim** 2023-09-11 11:48 UTC

**Comment by 0x5c** [comment] 2023-09-12 01:41
Just now got time to test, it seems fixed with .18
